module.exports.hanhChinh = [
    {
        ten: 'Hà Nội',
        loai: 'Thành phố trực thuộc trung ương',
        danSo: 8053663,
        thanhPhan: [
            {
                ten: 'Ba Đình',
                danSo: 247100,
                loai: 'Quận',
                thanhPhan: [
                    { ten: 'Cống Vị', danSo: 1, loai: 'Phường' },
                    { ten: 'Điện Biên', danSo: 1, loai: 'Phường' },
                    { ten: 'Đội Cấn', danSo: 1, loai: 'Phường' },
                    { ten: 'Giảng Võ', danSo: 1, loai: 'Phường' },
                    { ten: 'Kim Mã', danSo: 1, loai: 'Phường' },
                    { ten: 'Liễu Giai', danSo: 1, loai: 'Phường' },
                    { ten: 'Ngọc Hà', danSo: 1, loai: 'Phường' },
                    { ten: 'Ngọc Khánh', danSo: 1, loai: 'Phường' },
                    { ten: 'Nguyễn Trung Trực', danSo: 1, loai: 'Phường' },
                    { ten: 'Phúc Xá', danSo: 1, loai: 'Phường' },
                    { ten: 'Quán Thánh', danSo: 1, loai: 'Phường' },
                    { ten: 'Thành Công', danSo: 1, loai: 'Phường' },
                    { ten: 'Trúc Bạch', danSo: 1, loai: 'Phường' },
                    { ten: 'Vĩnh Phúc.', danSo: 1, loai: 'Phường' },
                ],
            },
            {
                ten: 'Bắc Từ Liêm',
                danSo: 333300,
                loai: 'Quận',
                thanhPhan: [
                    { ten: 'Cổ Nhuế 1', danSo: 1, loai: 'Phường' },
                    { ten: 'Cổ Nhuế 2', danSo: 1, loai: 'Phường' },
                    { ten: 'Đức Thắng', danSo: 1, loai: 'Phường' },
                    { ten: 'Đông Ngạc', danSo: 1, loai: 'Phường' },
                    { ten: 'Thụy Phương', danSo: 1, loai: 'Phường' },
                    { ten: 'Liên Mạc', danSo: 1, loai: 'Phường' },
                    { ten: 'Thượng Cát', danSo: 1, loai: 'Phường' },
                    { ten: 'Tây Tựu', danSo: 1, loai: 'Phường' },
                    { ten: 'Minh Khai', danSo: 1, loai: 'Phường' },
                    { ten: 'Phú Diễn', danSo: 1, loai: 'Phường' },
                    { ten: 'Phúc Diễn', danSo: 1, loai: 'Phường' },
                    { ten: 'Xuân Đỉnh', danSo: 1, loai: 'Phường' },
                    { ten: 'Xuân Tảo', danSo: 1, loai: 'Phường' },
                ],
            },
            {
                ten: 'Cầu Giấy',
                danSo: 266800,
                loai: 'Quận',
                thanhPhan: [
                    { ten: 'Dịch Vọng', danSo: 1, loai: 'Phường' },
                    { ten: 'Dịch Vọng Hậu', danSo: 1, loai: 'Phường' },
                    { ten: 'Mai Dịch', danSo: 1, loai: 'Phường' },
                    { ten: 'Nghĩa Đô', danSo: 1, loai: 'Phường' },
                    { ten: 'Nghĩa Tân', danSo: 1, loai: 'Phường' },
                    { ten: 'Quan Hoa', danSo: 1, loai: 'Phường' },
                    { ten: 'Trung Hòa', danSo: 1, loai: 'Phường' },
                    { ten: 'Yên Hòa', danSo: 1, loai: 'Phường' },
                ],
            },
            {
                ten: 'Đống Đa',
                danSo: 420900,
                loai: 'Quận',
                thanhPhan: [
                    { ten: 'Cát Linh', danSo: 1, loai: 'Phường' },
                    { ten: 'Hàng Bột', danSo: 1, loai: 'Phường' },
                    { ten: 'Khâm Thiên', danSo: 1, loai: 'Phường' },
                    { ten: 'Khương Thượng', danSo: 1, loai: 'Phường' },
                    { ten: 'Kim Liên', danSo: 1, loai: 'Phường' },
                    { ten: 'Láng Hạ', danSo: 1, loai: 'Phường' },
                    { ten: 'Láng Thượng', danSo: 1, loai: 'Phường' },
                    { ten: 'Nam Đồng', danSo: 1, loai: 'Phường' },
                    { ten: 'Ngã Tư Sở', danSo: 1, loai: 'Phường' },
                    { ten: 'Ô Chợ Dừa', danSo: 1, loai: 'Phường' },
                    { ten: 'Phương Liên', danSo: 1, loai: 'Phường' },
                    { ten: 'Phương Mai', danSo: 1, loai: 'Phường' },
                    { ten: 'Quang Trung', danSo: 1, loai: 'Phường' },
                    { ten: 'Quốc Tử Giám', danSo: 1, loai: 'Phường' },
                    { ten: 'Thịnh Quang', danSo: 1, loai: 'Phường' },
                    { ten: 'Thổ Quan', danSo: 1, loai: 'Phường' },
                    { ten: 'Trung Liệt', danSo: 1, loai: 'Phường' },
                    { ten: 'Trung Phụng', danSo: 1, loai: 'Phường' },
                    { ten: 'Trung Tự', danSo: 1, loai: 'Phường' },
                    { ten: 'Văn Chương', danSo: 1, loai: 'Phường' },
                    { ten: 'Văn Miếu', danSo: 1, loai: 'Phường' },
                ],
            },
            {
                ten: 'Hà Đông',
                danSo: 352000,
                loai: 'Quận',
                thanhPhan: [
                    { ten: 'Biên Giang', danSo: 1, loai: 'Phường' },
                    { ten: 'Đồng Mai', danSo: 1, loai: 'Phường' },
                    { ten: 'Yên Nghĩa', danSo: 1, loai: 'Phường' },
                    { ten: 'Dương Nội', danSo: 1, loai: 'Phường' },
                    { ten: 'Hà Cầu', danSo: 1, loai: 'Phường' },
                    { ten: 'La Khê', danSo: 1, loai: 'Phường' },
                    { ten: 'Mộ Lao', danSo: 1, loai: 'Phường' },
                    { ten: 'Nguyễn Trãi', danSo: 1, loai: 'Phường' },
                    { ten: 'Phú La', danSo: 1, loai: 'Phường' },
                    { ten: 'Phú Lãm', danSo: 1, loai: 'Phường' },
                    { ten: 'Phú Lương', danSo: 1, loai: 'Phường' },
                    { ten: 'Kiến Hưng', danSo: 1, loai: 'Phường' },
                    { ten: 'Phúc La', danSo: 1, loai: 'Phường' },
                    { ten: 'Quang Trung', danSo: 1, loai: 'Phường' },
                    { ten: 'Vạn Phúc', danSo: 1, loai: 'Phường' },
                    { ten: 'Văn Quán', danSo: 1, loai: 'Phường' },
                    { ten: 'Yết Kiêu', danSo: 1, loai: 'Phường' },
                ],
            },
            {
                ten: 'Hai Bà Trưng',
                danSo: 318000,
                loai: 'Quận',
                thanhPhan: [
                    { ten: 'Bách Khoa', danSo: 1, loai: 'Quận' },
                    { ten: 'Bạch Đằng', danSo: 1, loai: 'Quận' },
                    { ten: 'Bạch Mai', danSo: 1, loai: 'Quận' },
                    { ten: 'Cầu Dền', danSo: 1, loai: 'Quận' },
                    { ten: 'Đống Mác', danSo: 1, loai: 'Quận' },
                    { ten: 'Đồng Nhân', danSo: 1, loai: 'Quận' },
                    { ten: 'Đồng Tâm', danSo: 1, loai: 'Quận' },
                    { ten: 'Lê Đại Hành', danSo: 1, loai: 'Quận' },
                    { ten: 'Minh Khai', danSo: 1, loai: 'Quận' },
                    { ten: 'Nguyễn Du', danSo: 1, loai: 'Quận' },
                    { ten: 'Phạm Đình Hổ', danSo: 1, loai: 'Quận' },
                    { ten: 'Phố Huế', danSo: 1, loai: 'Quận' },
                    { ten: 'Quỳnh Lôi', danSo: 1, loai: 'Quận' },
                    { ten: 'Quỳnh Mai', danSo: 1, loai: 'Quận' },
                    { ten: 'Thanh Lương', danSo: 1, loai: 'Quận' },
                    { ten: 'Thanh Nhàn', danSo: 1, loai: 'Quận' },
                    { ten: 'Trương Định', danSo: 1, loai: 'Quận' },
                    { ten: 'Vĩnh Tuy', danSo: 1, loai: 'Quận' },
                ],
            },
            {
                ten: 'Hoàn Kiếm',
                danSo: 160600,
                loai: 'Quận',
                thanhPhan: [
                    { ten: 'Chương Dương', danSo: 1, loai: 'Quận' },
                    { ten: 'Cửa Đông', danSo: 1, loai: 'Quận' },
                    { ten: 'Cửa Nam', danSo: 1, loai: 'Quận' },
                    { ten: 'Đồng Xuân', danSo: 1, loai: 'Quận' },
                    { ten: 'Hàng Bạc', danSo: 1, loai: 'Quận' },
                    { ten: 'Hàng Bài', danSo: 1, loai: 'Quận' },
                    { ten: 'Hàng Bồ', danSo: 1, loai: 'Quận' },
                    { ten: 'Hàng Bông', danSo: 1, loai: 'Quận' },
                    { ten: 'Hàng Buồm', danSo: 1, loai: 'Quận' },
                    { ten: 'Hàng Đào', danSo: 1, loai: 'Quận' },
                    { ten: 'Hàng Gai', danSo: 1, loai: 'Quận' },
                    { ten: 'Hàng Mã', danSo: 1, loai: 'Quận' },
                    { ten: 'Hàng Trống', danSo: 1, loai: 'Quận' },
                    { ten: 'Lý Thái Tổ', danSo: 1, loai: 'Quận' },
                    { ten: 'Phan Chu Trinh', danSo: 1, loai: 'Quận' },
                    { ten: 'Phúc Tân', danSo: 1, loai: 'Quận' },
                    { ten: 'Trần Hưng Đạo', danSo: 1, loai: 'Quận' },
                    { ten: 'Tràng Tiền', danSo: 1, loai: 'Quận' },
                ],
            },
            {
                ten: 'Hoàng Mai',
                danSo: 411500,
                loai: 'Quận',
                thanhPhan: [
                    { ten: 'Đại Kim', danSo: 1, loai: 'Quận' },
                    { ten: 'Định Công', danSo: 1, loai: 'Quận' },
                    { ten: 'Giáp Bát', danSo: 1, loai: 'Quận' },
                    { ten: 'Hoàng Liệt', danSo: 1, loai: 'Quận' },
                    { ten: 'Hoàng Văn Thụ', danSo: 1, loai: 'Quận' },
                    { ten: 'Lĩnh Nam', danSo: 1, loai: 'Quận' },
                    { ten: 'Mai Động', danSo: 1, loai: 'Quận' },
                    { ten: 'Tân Mai', danSo: 1, loai: 'Quận' },
                    { ten: 'Thanh Trì', danSo: 1, loai: 'Quận' },
                    { ten: 'Thịnh Liệt', danSo: 1, loai: 'Quận' },
                    { ten: 'Trần Phú', danSo: 1, loai: 'Quận' },
                    { ten: 'Tương Mai', danSo: 1, loai: 'Quận' },
                    { ten: 'Vĩnh Hưng', danSo: 1, loai: 'Quận' },
                    { ten: 'Yên Sở', danSo: 1, loai: 'Quận' },
                ],
            },
            {
                ten: 'Long Biên',
                danSo: 291900,
                loai: 'Quận',
                thanhPhan: [
                    { ten: 'Bồ Đề', danSo: 1, loai: 'Quận' },
                    { ten: 'Cự Khối', danSo: 1, loai: 'Quận' },
                    { ten: 'Đức Giang', danSo: 1, loai: 'Quận' },
                    { ten: 'Gia Thụy', danSo: 1, loai: 'Quận' },
                    { ten: 'Giang Biên', danSo: 1, loai: 'Quận' },
                    { ten: 'Long Biên', danSo: 1, loai: 'Quận' },
                    { ten: 'Ngọc Lâm', danSo: 1, loai: 'Quận' },
                    { ten: 'Ngọc Thụy', danSo: 1, loai: 'Quận' },
                    { ten: 'Phúc Đồng', danSo: 1, loai: 'Quận' },
                    { ten: 'Phúc Lợi', danSo: 1, loai: 'Quận' },
                    { ten: 'Sài Đồng', danSo: 1, loai: 'Quận' },
                    { ten: 'Thạch Bàn', danSo: 1, loai: 'Quận' },
                    { ten: 'Thượng Thanh', danSo: 1, loai: 'Quận' },
                    { ten: 'Việt Hưng', danSo: 1, loai: 'Quận' },
                ],
            },
            {
                ten: 'Nam Từ Liêm',
                danSo: 236700,
                loai: 'Quận',
                thanhPhan: [
                    { ten: 'Cầu Diễn', danSo: 1, loai: 'Quận' },
                    { ten: 'Mỹ Đình 1', danSo: 1, loai: 'Quận' },
                    { ten: 'Mỹ Đình 2', danSo: 1, loai: 'Quận' },
                    { ten: 'Phú Đô', danSo: 1, loai: 'Quận' },
                    { ten: 'Mễ Trì', danSo: 1, loai: 'Quận' },
                    { ten: 'Trung Văn', danSo: 1, loai: 'Quận' },
                    { ten: 'Đại Mỗ', danSo: 1, loai: 'Quận' },
                    { ten: 'Tây Mỗ', danSo: 1, loai: 'Quận' },
                    { ten: 'Phương Canh', danSo: 1, loai: 'Quận' },
                    { ten: 'Xuân Phương', danSo: 1, loai: 'Quận' },
                ],
            },
            {
                ten: 'Tây Hồ',
                danSo: 168300,
                loai: 'Quận',
                thanhPhan: [
                    { ten: 'Bưởi', danSo: 1, loai: 'Quận' },
                    { ten: 'Nhật Tân', danSo: 1, loai: 'Quận' },
                    { ten: 'Phú Thượng', danSo: 1, loai: 'Quận' },
                    { ten: 'Quảng An', danSo: 1, loai: 'Quận' },
                    { ten: 'Thụy Khuê', danSo: 1, loai: 'Quận' },
                    { ten: 'Tứ Liên', danSo: 1, loai: 'Quận' },
                    { ten: 'Xuân La', danSo: 1, loai: 'Quận' },
                    { ten: 'Yên Phụ', danSo: 1, loai: 'Quận' },
                ],
            },
            {
                ten: 'Thanh Xuân',
                danSo: 285400,
                loai: 'Quận',
                thanhPhan: [
                    { ten: 'Hạ Đình', danSo: 1, loai: 'Quận' },
                    { ten: 'Khương Đình', danSo: 1, loai: 'Quận' },
                    { ten: 'Khương Mai', danSo: 1, loai: 'Quận' },
                    { ten: 'Khương Trung', danSo: 1, loai: 'Quận' },
                    { ten: 'Kim Giang', danSo: 1, loai: 'Quận' },
                    { ten: 'Nhân Chính', danSo: 1, loai: 'Quận' },
                    { ten: 'Phương Liệt', danSo: 1, loai: 'Quận' },
                    { ten: 'Thanh Xuân Bắc', danSo: 1, loai: 'Quận' },
                    { ten: 'Thanh Xuân Nam', danSo: 1, loai: 'Quận' },
                    { ten: 'Thanh Xuân Trung', danSo: 1, loai: 'Quận' },
                    { ten: 'Thượng Đình', danSo: 1, loai: 'Quận' },
                ],
            },
            {
                ten: 'Sơn Tây',
                danSo: 230577,
                loai: 'Thị xã',
                thanhPhan: [
                    { ten: 'Lê Lợi', danSo: 1, loai: 'Phường' },
                    { ten: 'Ngô Quyền', danSo: 1, loai: 'Phường' },
                    { ten: 'Phú Thịnh', danSo: 1, loai: 'Phường' },
                    { ten: 'Quang Trung', danSo: 1, loai: 'Phường' },
                    { ten: 'Sơn Lộc', danSo: 1, loai: 'Phường' },
                    { ten: 'Trung Hưng', danSo: 1, loai: 'Phường' },
                    { ten: 'Trung Sơn Trầm', danSo: 1, loai: 'Phường' },
                    { ten: 'Viên Sơn', danSo: 1, loai: 'Phường' },
                    { ten: 'Xuân Khanh và 6 xã: Cổ Đông', danSo: 1, loai: 'Phường' },
                    { ten: 'Đường Lâm', danSo: 1, loai: 'Phường' },
                    { ten: 'Kim Sơn', danSo: 1, loai: 'Phường' },
                    { ten: 'Sơn Đông', danSo: 1, loai: 'Phường' },
                    { ten: 'Thanh Mỹ', danSo: 1, loai: 'Phường' },
                    { ten: 'Xuân Sơn', danSo: 1, loai: 'Phường' },
                ],
            },
            {
                ten: 'Ba Vì',
                danSo: 282600,
                loai: 'Huyện',
                thanhPhan: [
                    { ten: 'Tây Đằng', danSo: 1, loai: 'Thị trấn' },
                    { ten: 'Ba Trại', danSo: 1, loai: 'Xã' },
                    { ten: 'Ba Vì', danSo: 1, loai: 'Xã' },
                    { ten: 'Cẩm Lĩnh', danSo: 1, loai: 'Xã' },
                    { ten: 'Cam Thượng', danSo: 1, loai: 'Xã' },
                    { ten: 'Châu Sơn', danSo: 1, loai: 'Xã' },
                    { ten: 'Chu Minh', danSo: 1, loai: 'Xã' },
                    { ten: 'Cổ Đô', danSo: 1, loai: 'Xã' },
                    { ten: 'Đông Quang', danSo: 1, loai: 'Xã' },
                    { ten: 'Đồng Thái', danSo: 1, loai: 'Xã' },
                    { ten: 'Khánh Thượng', danSo: 1, loai: 'Xã' },
                    { ten: 'Minh Châu', danSo: 1, loai: 'Xã' },
                    { ten: 'Minh Quang', danSo: 1, loai: 'Xã' },
                    { ten: 'Phong Vân', danSo: 1, loai: 'Xã' },
                    { ten: 'Phú Châu', danSo: 1, loai: 'Xã' },
                    { ten: 'Phú Cường', danSo: 1, loai: 'Xã' },
                    { ten: 'Phú Đông', danSo: 1, loai: 'Xã' },
                    { ten: 'Phú Phương', danSo: 1, loai: 'Xã' },
                    { ten: 'Phú Sơn', danSo: 1, loai: 'Xã' },
                    { ten: 'Sơn Đà', danSo: 1, loai: 'Xã' },
                    { ten: 'Tản Hồng', danSo: 1, loai: 'Xã' },
                    { ten: 'Tản Lĩnh', danSo: 1, loai: 'Xã' },
                    { ten: 'Thái Hòa', danSo: 1, loai: 'Xã' },
                    { ten: 'Thuần Mỹ', danSo: 1, loai: 'Xã' },
                    { ten: 'Thụy An', danSo: 1, loai: 'Xã' },
                    { ten: 'Tiên Phong', danSo: 1, loai: 'Xã' },
                    { ten: 'Tòng Bạt', danSo: 1, loai: 'Xã' },
                    { ten: 'Vân Hòa', danSo: 1, loai: 'Xã' },
                    { ten: 'Vạn Thắng', danSo: 1, loai: 'Xã' },
                    { ten: 'Vật Lại', danSo: 1, loai: 'Xã' },
                    { ten: 'Yên Bài', danSo: 1, loai: 'Xã' },
                ],
            },
            {
                ten: 'Chương Mỹ',
                danSo: 330000,
                loai: 'Huyện',
                thanhPhan: [
                    { ten: 'Chúc Sơn', danSo: 1, loai: 'Thị trấn' },
                    { ten: 'Xuân Mai ', danSo: 1, loai: 'Thị trấn' },
                    { ten: 'Đại Yên', danSo: 1, loai: 'Xã' },
                    { ten: 'Đông Phương Yên', danSo: 1, loai: 'Xã' },
                    { ten: 'Đông Sơn', danSo: 1, loai: 'Xã' },
                    { ten: 'Đồng Lạc', danSo: 1, loai: 'Xã' },
                    { ten: 'Đồng Phú', danSo: 1, loai: 'Xã' },
                    { ten: 'Hòa Chính', danSo: 1, loai: 'Xã' },
                    { ten: 'Hoàng Diệu', danSo: 1, loai: 'Xã' },
                    { ten: 'Hoàng Văn Thụ', danSo: 1, loai: 'Xã' },
                    { ten: 'Hồng Phong', danSo: 1, loai: 'Xã' },
                    { ten: 'Hợp Đồng', danSo: 1, loai: 'Xã' },
                    { ten: 'Hữu Văn', danSo: 1, loai: 'Xã' },
                    { ten: 'Lam Điền', danSo: 1, loai: 'Xã' },
                    { ten: 'Mỹ Lương', danSo: 1, loai: 'Xã' },
                    { ten: 'Nam Phương Tiến', danSo: 1, loai: 'Xã' },
                    { ten: 'Ngọc Hòa', danSo: 1, loai: 'Xã' },
                    { ten: 'Phú Nam An', danSo: 1, loai: 'Xã' },
                    { ten: 'Phú Nghĩa', danSo: 1, loai: 'Xã' },
                    { ten: 'Phụng Châu', danSo: 1, loai: 'Xã' },
                    { ten: 'Quảng Bị', danSo: 1, loai: 'Xã' },
                    { ten: 'Tân Tiến', danSo: 1, loai: 'Xã' },
                    { ten: 'Tiên Phương', danSo: 1, loai: 'Xã' },
                    { ten: 'Tốt Động', danSo: 1, loai: 'Xã' },
                    { ten: 'Thanh Bình', danSo: 1, loai: 'Xã' },
                    { ten: 'Thủy Xuân Tiên', danSo: 1, loai: 'Xã' },
                    { ten: 'Thụy Hương', danSo: 1, loai: 'Xã' },
                    { ten: 'Thượng Vực', danSo: 1, loai: 'Xã' },
                    { ten: 'Trần Phú', danSo: 1, loai: 'Xã' },
                    { ten: 'Trung Hòa', danSo: 1, loai: 'Xã' },
                    { ten: 'Trường Yên', danSo: 1, loai: 'Xã' },
                    { ten: 'Văn Võ', danSo: 1, loai: 'Xã' },
                ],
            },
            {
                ten: 'Đan Phượng',
                danSo: 162900,
                loai: 'Huyện',
                thanhPhan: [
                    { ten: 'Phùng', danSo: 1, loai: 'Thị trấn' },
                    { ten: 'Đan Phượng', danSo: 1, loai: 'Xã' },
                    { ten: 'Đồng Tháp', danSo: 1, loai: 'Xã' },
                    { ten: 'Hạ Mỗ', danSo: 1, loai: 'Xã' },
                    { ten: 'Hồng Hà', danSo: 1, loai: 'Xã' },
                    { ten: 'Liên Hà', danSo: 1, loai: 'Xã' },
                    { ten: 'Liên Hồng', danSo: 1, loai: 'Xã' },
                    { ten: 'Liên Trung', danSo: 1, loai: 'Xã' },
                    { ten: 'Phương Đình', danSo: 1, loai: 'Xã' },
                    { ten: 'Song Phượng', danSo: 1, loai: 'Xã' },
                    { ten: 'Tân Hội', danSo: 1, loai: 'Xã' },
                    { ten: 'Tân Lập', danSo: 1, loai: 'Xã' },
                    { ten: 'Thọ An', danSo: 1, loai: 'Xã' },
                    { ten: 'Thọ Xuân', danSo: 1, loai: 'Xã' },
                    { ten: 'Thượng Mỗ', danSo: 1, loai: 'Xã' },
                    { ten: 'Trung Châu', danSo: 1, loai: 'Xã' },
                ],
            },
            {
                ten: 'Đông Anh',
                danSo: 381500,
                loai: 'Huyện',
                thanhPhan: [
                    { ten: 'Đông Anh', danSo: 1, loai: 'Thị trấn' },
                    { ten: 'Bắc Hồng', danSo: 1, loai: 'Xã' },
                    { ten: 'Cổ Loa', danSo: 1, loai: 'Xã' },
                    { ten: 'Đại Mạch', danSo: 1, loai: 'Xã' },
                    { ten: 'Đông Hội', danSo: 1, loai: 'Xã' },
                    { ten: 'Dục Tú', danSo: 1, loai: 'Xã' },
                    { ten: 'Hải Bối', danSo: 1, loai: 'Xã' },
                    { ten: 'Kim Chung', danSo: 1, loai: 'Xã' },
                    { ten: 'Kim Nỗ', danSo: 1, loai: 'Xã' },
                    { ten: 'Liên Hà', danSo: 1, loai: 'Xã' },
                    { ten: 'Mai Lâm', danSo: 1, loai: 'Xã' },
                    { ten: 'Nam Hồng', danSo: 1, loai: 'Xã' },
                    { ten: 'Nguyên Khê', danSo: 1, loai: 'Xã' },
                    { ten: 'Tàm Xá', danSo: 1, loai: 'Xã' },
                    { ten: 'Thụy Lâm', danSo: 1, loai: 'Xã' },
                    { ten: 'Tiên Dương', danSo: 1, loai: 'Xã' },
                    { ten: 'Uy Nỗ', danSo: 1, loai: 'Xã' },
                    { ten: 'Vân Hà', danSo: 1, loai: 'Xã' },
                    { ten: 'Vân Nội', danSo: 1, loai: 'Xã' },
                    { ten: 'Việt Hùng', danSo: 1, loai: 'Xã' },
                    { ten: 'Vĩnh Ngọc', danSo: 1, loai: 'Xã' },
                    { ten: 'Võng La', danSo: 1, loai: 'Xã' },
                    { ten: 'Xuân Canh', danSo: 1, loai: 'Xã' },
                    { ten: 'Xuân Nộn', danSo: 1, loai: 'Xã' },
                ],
            },
            {
                ten: 'Gia Lâm',
                danSo: 277600,
                loai: 'Huyện',
                thanhPhan: [
                    { ten: 'Trâu Quỳ', danSo: 1, loai: 'Thị trấn' },
                    { ten: 'Yên Viên', danSo: 1, loai: 'Xã' },
                    { ten: 'Bát Tràng', danSo: 1, loai: 'Xã' },
                    { ten: 'Cổ Bi', danSo: 1, loai: 'Xã' },
                    { ten: 'Đa Tốn', danSo: 1, loai: 'Xã' },
                    { ten: 'Đặng Xá', danSo: 1, loai: 'Xã' },
                    { ten: 'Phú Thị', danSo: 1, loai: 'Xã' },
                    { ten: 'Đông Dư', danSo: 1, loai: 'Xã' },
                    { ten: 'Dương Hà', danSo: 1, loai: 'Xã' },
                    { ten: 'Dương Quang', danSo: 1, loai: 'Xã' },
                    { ten: 'Dương Xá', danSo: 1, loai: 'Xã' },
                    { ten: 'Kiêu Kỵ', danSo: 1, loai: 'Xã' },
                    { ten: 'Kim Lan', danSo: 1, loai: 'Xã' },
                    { ten: 'Văn Đức', danSo: 1, loai: 'Xã' },
                    { ten: 'Lệ Chi', danSo: 1, loai: 'Xã' },
                    { ten: 'Ninh Hiệp', danSo: 1, loai: 'Xã' },
                    { ten: 'Đình Xuyên', danSo: 1, loai: 'Xã' },
                    { ten: 'Phù Đổng', danSo: 1, loai: 'Xã' },
                    { ten: 'Trung Mầu', danSo: 1, loai: 'Xã' },
                    { ten: 'Yên Thường', danSo: 1, loai: 'Xã' },
                    { ten: 'Yên Viên', danSo: 1, loai: 'Xã' },
                    { ten: 'Kim Sơn', danSo: 1, loai: 'Xã' },
                ],
            },
            {
                ten: 'Hoài Đức',
                danSo: 229400,
                loai: 'Huyện',
                thanhPhan: [
                    { ten: 'Trạm Trôi', danSo: 1, loai: 'Thị trấn' },
                    { ten: 'An Khánh', danSo: 1, loai: 'Xã' },
                    { ten: 'An Thượng', danSo: 1, loai: 'Xã' },
                    { ten: 'Cát Quế', danSo: 1, loai: 'Xã' },
                    { ten: 'Đắc Sở', danSo: 1, loai: 'Xã' },
                    { ten: 'Di Trạch', danSo: 1, loai: 'Xã' },
                    { ten: 'Đông La', danSo: 1, loai: 'Xã' },
                    { ten: 'Đức Giang', danSo: 1, loai: 'Xã' },
                    { ten: 'Đức Thượng', danSo: 1, loai: 'Xã' },
                    { ten: 'Dương Liễu', danSo: 1, loai: 'Xã' },
                    { ten: 'Kim Chung', danSo: 1, loai: 'Xã' },
                    { ten: 'La Phù', danSo: 1, loai: 'Xã' },
                    { ten: 'Lại Yên', danSo: 1, loai: 'Xã' },
                    { ten: 'Minh Khai', danSo: 1, loai: 'Xã' },
                    { ten: 'Sơn Đồng', danSo: 1, loai: 'Xã' },
                    { ten: 'Song Phương', danSo: 1, loai: 'Xã' },
                    { ten: 'Tiền Yên', danSo: 1, loai: 'Xã' },
                    { ten: 'Vân Canh', danSo: 1, loai: 'Xã' },
                    { ten: 'Vân Côn', danSo: 1, loai: 'Xã' },
                    { ten: 'Yên Sở', danSo: 1, loai: 'Xã' },
                ],
            },
            {
                ten: 'Mê Linh',
                danSo: 226800,
                loai: 'Huyện',
                thanhPhan: [
                    { ten: 'Chi Đông', danSo: 1, loai: 'Thị trấn' },
                    { ten: 'Quang Minh', danSo: 1, loai: 'Xã' },
                    { ten: 'Chu Phan', danSo: 1, loai: 'Xã' },
                    { ten: 'Đại Thịnh', danSo: 1, loai: 'Xã' },
                    { ten: 'Hoàng Kim', danSo: 1, loai: 'Xã' },
                    { ten: 'Kim Hoa', danSo: 1, loai: 'Xã' },
                    { ten: 'Liên Mạc', danSo: 1, loai: 'Xã' },
                    { ten: 'Mê Linh', danSo: 1, loai: 'Xã' },
                    { ten: 'Tam Đồng', danSo: 1, loai: 'Xã' },
                    { ten: 'Thạch Đà', danSo: 1, loai: 'Xã' },
                    { ten: 'Thanh Lâm', danSo: 1, loai: 'Xã' },
                    { ten: 'Tiền Phong', danSo: 1, loai: 'Xã' },
                    { ten: 'Tiến Thắng', danSo: 1, loai: 'Xã' },
                    { ten: 'Tiến Thịnh', danSo: 1, loai: 'Xã' },
                    { ten: 'Tráng Việt', danSo: 1, loai: 'Xã' },
                    { ten: 'Tự Lập', danSo: 1, loai: 'Xã' },
                    { ten: 'Vạn Yên', danSo: 1, loai: 'Xã' },
                    { ten: 'Văn Khê', danSo: 1, loai: 'Xã' },
                ],
            },
            {
                ten: 'Mỹ Đức',
                danSo: 194400,
                loai: 'Huyện',
                thanhPhan: [
                    { ten: 'Đại Nghĩa', danSo: 1, loai: 'Thị trấn' },
                    { ten: 'An Mỹ', danSo: 1, loai: 'Xã' },
                    { ten: 'An Phú', danSo: 1, loai: 'Xã' },
                    { ten: 'An Tiến', danSo: 1, loai: 'Xã' },
                    { ten: 'Bột Xuyên', danSo: 1, loai: 'Xã' },
                    { ten: 'Đại Hưng', danSo: 1, loai: 'Xã' },
                    { ten: 'Đốc Tín', danSo: 1, loai: 'Xã' },
                    { ten: 'Đồng Tâm', danSo: 1, loai: 'Xã' },
                    { ten: 'Hồng Sơn', danSo: 1, loai: 'Xã' },
                    { ten: 'Hợp Thanh', danSo: 1, loai: 'Xã' },
                    { ten: 'Hợp Tiến', danSo: 1, loai: 'Xã' },
                    { ten: 'Hùng Tiến', danSo: 1, loai: 'Xã' },
                    { ten: 'Hương Sơn', danSo: 1, loai: 'Xã' },
                    { ten: 'Lê Thanh', danSo: 1, loai: 'Xã' },
                    { ten: 'Mỹ Thành', danSo: 1, loai: 'Xã' },
                    { ten: 'Phù Lưu Tế', danSo: 1, loai: 'Xã' },
                    { ten: 'Phúc Lâm', danSo: 1, loai: 'Xã' },
                    { ten: 'Phùng Xá', danSo: 1, loai: 'Xã' },
                    { ten: 'Thượng Lâm', danSo: 1, loai: 'Xã' },
                    { ten: 'Tuy Lai', danSo: 1, loai: 'Xã' },
                    { ten: 'Vạn Kim', danSo: 1, loai: 'Xã' },
                    { ten: 'Xuy Xá', danSo: 1, loai: 'Xã' },
                ],
            },
            {
                ten: 'Phú Xuyên',
                danSo: 211100,
                loai: 'Huyện',
                thanhPhan: [
                    { ten: 'Phú Xuyên', danSo: 1, loai: 'Thị trấn' },
                    { ten: 'Phú Minh', danSo: 1, loai: 'Thị trấn' },
                    { ten: 'Bạch Hạ', danSo: 1, loai: 'Xã' },
                    { ten: 'Châu Can', danSo: 1, loai: 'Xã' },
                    { ten: 'Chuyên Mỹ', danSo: 1, loai: 'Xã' },
                    { ten: 'Đại Thắng', danSo: 1, loai: 'Xã' },
                    { ten: 'Đại Xuyên', danSo: 1, loai: 'Xã' },
                    { ten: 'Hoàng Long', danSo: 1, loai: 'Xã' },
                    { ten: 'Hồng Minh', danSo: 1, loai: 'Xã' },
                    { ten: 'Hồng Thái', danSo: 1, loai: 'Xã' },
                    { ten: 'Khai Thái', danSo: 1, loai: 'Xã' },
                    { ten: 'Minh Tân', danSo: 1, loai: 'Xã' },
                    { ten: 'Nam Phong', danSo: 1, loai: 'Xã' },
                    { ten: 'Nam Tiến', danSo: 1, loai: 'Xã' },
                    { ten: 'Nam Triều', danSo: 1, loai: 'Xã' },
                    { ten: 'Phú Túc', danSo: 1, loai: 'Xã' },
                    { ten: 'Phú Yên', danSo: 1, loai: 'Xã' },
                    { ten: 'Phúc Tiến', danSo: 1, loai: 'Xã' },
                    { ten: 'Phượng Dực', danSo: 1, loai: 'Xã' },
                    { ten: 'Quang Lãng', danSo: 1, loai: 'Xã' },
                    { ten: 'Quang Trung', danSo: 1, loai: 'Xã' },
                    { ten: 'Sơn Hà', danSo: 1, loai: 'Xã' },
                    { ten: 'Tân Dân', danSo: 1, loai: 'Xã' },
                    { ten: 'Tri Thủy', danSo: 1, loai: 'Xã' },
                    { ten: 'Tri Trung', danSo: 1, loai: 'Xã' },
                    { ten: 'Văn Hoàng', danSo: 1, loai: 'Xã' },
                    { ten: 'Vân Từ', danSo: 1, loai: 'Xã' },
                ],
            },
            {
                ten: 'Phúc Thọ',
                danSo: 182300,
                loai: 'Huyện',
                thanhPhan: [
                    { ten: 'Phúc Thọ', danSo: 1, loai: 'Thị trấn' },
                    { ten: 'Hát Môn', danSo: 1, loai: 'Xã' },
                    { ten: 'Hiệp Thuận', danSo: 1, loai: 'Xã' },
                    { ten: 'Liên Hiệp', danSo: 1, loai: 'Xã' },
                    { ten: 'Long Xuyên', danSo: 1, loai: 'Xã' },
                    { ten: 'Ngọc Tảo', danSo: 1, loai: 'Xã' },
                    { ten: 'Phúc Hòa', danSo: 1, loai: 'Xã' },
                    { ten: 'Phụng Thượng', danSo: 1, loai: 'Xã' },
                    { ten: 'Sen Phương', danSo: 1, loai: 'Xã' },
                    { ten: 'Tam Hiệp', danSo: 1, loai: 'Xã' },
                    { ten: 'Tam Thuấn', danSo: 1, loai: 'Xã' },
                    { ten: 'Thanh Đa', danSo: 1, loai: 'Xã' },
                    { ten: 'Thọ Lộc', danSo: 1, loai: 'Xã' },
                    { ten: 'Thượng Cốc', danSo: 1, loai: 'Xã' },
                    { ten: 'Tích Giang', danSo: 1, loai: 'Xã' },
                    { ten: 'Trạch Mỹ Lộc', danSo: 1, loai: 'Xã' },
                    { ten: 'Vân Hà', danSo: 1, loai: 'Xã' },
                    { ten: 'Vân Nam', danSo: 1, loai: 'Xã' },
                    { ten: 'Vân Phúc', danSo: 1, loai: 'Xã' },
                    { ten: 'Võng Xuyên', danSo: 1, loai: 'Xã' },
                    { ten: 'Xuân Đình', danSo: 1, loai: 'Xã' },
                ],
            },
            {
                ten: 'Quốc Oai',
                danSo: 188000,
                loai: 'Huyện',
                thanhPhan: [
                    { ten: 'Quốc Oai', danSo: 1, loai: 'Thị trấn' },
                    { ten: 'Cấn Hữu', danSo: 1, loai: 'Xã' },
                    { ten: 'Cộng Hòa', danSo: 1, loai: 'Xã' },
                    { ten: 'Đại Thành', danSo: 1, loai: 'Xã' },
                    { ten: 'Đồng Quang', danSo: 1, loai: 'Xã' },
                    { ten: 'Đông Yên', danSo: 1, loai: 'Xã' },
                    { ten: 'Hòa Thạch', danSo: 1, loai: 'Xã' },
                    { ten: 'Liệp Tuyết', danSo: 1, loai: 'Xã' },
                    { ten: 'Nghĩa Hương', danSo: 1, loai: 'Xã' },
                    { ten: 'Ngọc Liệp', danSo: 1, loai: 'Xã' },
                    { ten: 'Ngọc Mỹ', danSo: 1, loai: 'Xã' },
                    { ten: 'Phú Cát', danSo: 1, loai: 'Xã' },
                    { ten: 'Phú Mãn', danSo: 1, loai: 'Xã' },
                    { ten: 'Phượng Cách', danSo: 1, loai: 'Xã' },
                    { ten: 'Sài Sơn', danSo: 1, loai: 'Xã' },
                    { ten: 'Tân Hòa', danSo: 1, loai: 'Xã' },
                    { ten: 'Tân Phú', danSo: 1, loai: 'Xã' },
                    { ten: 'Thạch Thán', danSo: 1, loai: 'Xã' },
                    { ten: 'Tuyết Nghĩa', danSo: 1, loai: 'Xã' },
                    { ten: 'Yên Sơn', danSo: 1, loai: 'Xã' },
                    { ten: 'Đông Xuân', danSo: 1, loai: 'Xã' },
                ],
            },
            {
                ten: 'Sóc Sơn',
                danSo: 340700,
                loai: 'Huyện',
                thanhPhan: [
                    { ten: 'Sóc Sơn', danSo: 1, loai: 'Thị trấn' },
                    { ten: 'Bắc Phú', danSo: 1, loai: 'Xã' },
                    { ten: 'Bắc Sơn', danSo: 1, loai: 'Xã' },
                    { ten: 'Đông Xuân', danSo: 1, loai: 'Xã' },
                    { ten: 'Đức Hòa', danSo: 1, loai: 'Xã' },
                    { ten: 'Hiền Ninh', danSo: 1, loai: 'Xã' },
                    { ten: 'Hồng Kỳ', danSo: 1, loai: 'Xã' },
                    { ten: 'Kim Lũ', danSo: 1, loai: 'Xã' },
                    { ten: 'Mai Đình', danSo: 1, loai: 'Xã' },
                    { ten: 'Minh Phú', danSo: 1, loai: 'Xã' },
                    { ten: 'Minh Trí', danSo: 1, loai: 'Xã' },
                    { ten: 'Nam Sơn', danSo: 1, loai: 'Xã' },
                    { ten: 'Phú Cường', danSo: 1, loai: 'Xã' },
                    { ten: 'Phù Linh', danSo: 1, loai: 'Xã' },
                    { ten: 'Phù Lỗ', danSo: 1, loai: 'Xã' },
                    { ten: 'Phú Minh', danSo: 1, loai: 'Xã' },
                    { ten: 'Quang Tiến', danSo: 1, loai: 'Xã' },
                    { ten: 'Tân Dân', danSo: 1, loai: 'Xã' },
                    { ten: 'Tân Hưng', danSo: 1, loai: 'Xã' },
                    { ten: 'Tân Minh', danSo: 1, loai: 'Xã' },
                    { ten: 'Thanh Xuân', danSo: 1, loai: 'Xã' },
                    { ten: 'Tiên Dược', danSo: 1, loai: 'Xã' },
                    { ten: 'Trung Giã', danSo: 1, loai: 'Xã' },
                    { ten: 'Việt Long', danSo: 1, loai: 'Xã' },
                    { ten: 'Xuân Giang', danSo: 1, loai: 'Xã' },
                    { ten: 'Xuân Thu', danSo: 1, loai: 'Xã' },
                ],
            },
            {
                ten: 'Thạch Thất',
                danSo: 207500,
                loai: 'Huyện',
                thanhPhan: [
                    { ten: 'Liên Quan', danSo: 1, loai: 'Thị trấn' },
                    { ten: 'Bình Phú', danSo: 1, loai: 'Xã' },
                    { ten: 'Bình Yên', danSo: 1, loai: 'Xã' },
                    { ten: 'Cẩm Yên', danSo: 1, loai: 'Xã' },
                    { ten: 'Cần Kiệm', danSo: 1, loai: 'Xã' },
                    { ten: 'Canh Nậu', danSo: 1, loai: 'Xã' },
                    { ten: 'Chàng Sơn', danSo: 1, loai: 'Xã' },
                    { ten: 'Đại Đồng', danSo: 1, loai: 'Xã' },
                    { ten: 'Dị Nậu', danSo: 1, loai: 'Xã' },
                    { ten: 'Đồng Trúc', danSo: 1, loai: 'Xã' },
                    { ten: 'Hạ Bằng', danSo: 1, loai: 'Xã' },
                    { ten: 'Hương Ngải', danSo: 1, loai: 'Xã' },
                    { ten: 'Hữu Bằng', danSo: 1, loai: 'Xã' },
                    { ten: 'Kim Quan', danSo: 1, loai: 'Xã' },
                    { ten: 'Lại Thượng', danSo: 1, loai: 'Xã' },
                    { ten: 'Phú Kim', danSo: 1, loai: 'Xã' },
                    { ten: 'Phùng Xá', danSo: 1, loai: 'Xã' },
                    { ten: 'Tân Xã', danSo: 1, loai: 'Xã' },
                    { ten: 'Thạch Hòa', danSo: 1, loai: 'Xã' },
                    { ten: 'Thạch Xá', danSo: 1, loai: 'Xã' },
                    { ten: 'Tiến Xuân', danSo: 1, loai: 'Xã' },
                    { ten: 'Yên Bình', danSo: 1, loai: 'Xã' },
                    { ten: 'Yên Trung', danSo: 1, loai: 'Xã' },
                ],
            },
            {
                ten: 'Thanh Oai',
                danSo: 205200,
                loai: 'Huyện',
                thanhPhan: [
                    { ten: 'Kim Bài', danSo: 1, loai: 'Thị trấn' },
                    { ten: 'Bích Hòa', danSo: 1, loai: 'Xã' },
                    { ten: 'Bình Minh', danSo: 1, loai: 'Xã' },
                    { ten: 'Cao Dương', danSo: 1, loai: 'Xã' },
                    { ten: 'Cao Viên', danSo: 1, loai: 'Xã' },
                    { ten: 'Cự Khê', danSo: 1, loai: 'Xã' },
                    { ten: 'Dân Hòa', danSo: 1, loai: 'Xã' },
                    { ten: 'Đỗ Động', danSo: 1, loai: 'Xã' },
                    { ten: 'Hồng Dương', danSo: 1, loai: 'Xã' },
                    { ten: 'Kim An', danSo: 1, loai: 'Xã' },
                    { ten: 'Kim Thư', danSo: 1, loai: 'Xã' },
                    { ten: 'Liên Châu', danSo: 1, loai: 'Xã' },
                    { ten: 'Mỹ Hưng', danSo: 1, loai: 'Xã' },
                    { ten: 'Phương Trung', danSo: 1, loai: 'Xã' },
                    { ten: 'Tam Hưng', danSo: 1, loai: 'Xã' },
                    { ten: 'Tân Ước', danSo: 1, loai: 'Xã' },
                    { ten: 'Thanh Cao', danSo: 1, loai: 'Xã' },
                    { ten: 'Thanh Mai', danSo: 1, loai: 'Xã' },
                    { ten: 'Thanh Thùy', danSo: 1, loai: 'Xã' },
                    { ten: 'Thanh Văn', danSo: 1, loai: 'Xã' },
                    { ten: 'Xuân Dương', danSo: 1, loai: 'Xã' },
                ],
            },
            {
                ten: 'Thanh Trì',
                danSo: 256800,
                loai: 'Huyện',
                thanhPhan: [
                    { ten: 'Văn Điển', danSo: 1, loai: 'Thị trấn' },
                    { ten: 'Đại Áng', danSo: 1, loai: 'Xã' },
                    { ten: 'Đông Mỹ', danSo: 1, loai: 'Xã' },
                    { ten: 'Duyên Hà', danSo: 1, loai: 'Xã' },
                    { ten: 'Hữu Hòa', danSo: 1, loai: 'Xã' },
                    { ten: 'Liên Ninh', danSo: 1, loai: 'Xã' },
                    { ten: 'Ngọc Hồi', danSo: 1, loai: 'Xã' },
                    { ten: 'Ngũ Hiệp', danSo: 1, loai: 'Xã' },
                    { ten: 'Tả Thanh Oai', danSo: 1, loai: 'Xã' },
                    { ten: 'Tam Hiệp', danSo: 1, loai: 'Xã' },
                    { ten: 'Tân Triều', danSo: 1, loai: 'Xã' },
                    { ten: 'Thanh Liệt', danSo: 1, loai: 'Xã' },
                    { ten: 'Tứ Hiệp', danSo: 1, loai: 'Xã' },
                    { ten: 'Vạn Phúc', danSo: 1, loai: 'Xã' },
                    { ten: 'Vĩnh Quỳnh', danSo: 1, loai: 'Xã' },
                    { ten: 'Yên Mỹ', danSo: 1, loai: 'Xã' },
                ],
            },
            {
                ten: 'Thường Tín',
                danSo: 247700,
                loai: 'Huyện',
                thanhPhan: [
                    { ten: 'Thường Tín', danSo: 1, loai: 'Thị trấn' },
                    { ten: 'Chương Dương', danSo: 1, loai: 'Xã' },
                    { ten: 'Dũng Tiến', danSo: 1, loai: 'Xã' },
                    { ten: 'Duyên Thái', danSo: 1, loai: 'Xã' },
                    { ten: 'Hà Hồi', danSo: 1, loai: 'Xã' },
                    { ten: 'Hiền Giang', danSo: 1, loai: 'Xã' },
                    { ten: 'Hòa Bình', danSo: 1, loai: 'Xã' },
                    { ten: 'Khánh Hà', danSo: 1, loai: 'Xã' },
                    { ten: 'Hồng Vân', danSo: 1, loai: 'Xã' },
                    { ten: 'Lê Lợi', danSo: 1, loai: 'Xã' },
                    { ten: 'Liên Phương', danSo: 1, loai: 'Xã' },
                    { ten: 'Minh Cường', danSo: 1, loai: 'Xã' },
                    { ten: 'Nghiêm Xuyên', danSo: 1, loai: 'Xã' },
                    { ten: 'Nguyễn Trãi', danSo: 1, loai: 'Xã' },
                    { ten: 'Nhị Khê', danSo: 1, loai: 'Xã' },
                    { ten: 'Ninh Sở', danSo: 1, loai: 'Xã' },
                    { ten: 'Quất Động', danSo: 1, loai: 'Xã' },
                    { ten: 'Tân Minh', danSo: 1, loai: 'Xã' },
                    { ten: 'Thắng Lợi', danSo: 1, loai: 'Xã' },
                    { ten: 'Thống Nhất', danSo: 1, loai: 'Xã' },
                    { ten: 'Thư Phú', danSo: 1, loai: 'Xã' },
                    { ten: 'Tiền Phong', danSo: 1, loai: 'Xã' },
                    { ten: 'Tô Hiệu', danSo: 1, loai: 'Xã' },
                    { ten: 'Tự Nhiên', danSo: 1, loai: 'Xã' },
                    { ten: 'Vạn Điểm', danSo: 1, loai: 'Xã' },
                    { ten: 'Văn Bình', danSo: 1, loai: 'Xã' },
                    { ten: 'Văn Phú', danSo: 1, loai: 'Xã' },
                    { ten: 'Văn Tự', danSo: 1, loai: 'Xã' },
                    { ten: 'Vân Tảo', danSo: 1, loai: 'Xã' },
                ],
            },
            {
                ten: 'Ứng Hòa',
                danSo: 204800,
                loai: 'Huyện',
                thanhPhan: [
                    { ten: 'Vân Đình', danSo: 1, loai: 'Thị trấn' },
                    { ten: 'Cao Thành', danSo: 1, loai: 'Xã' },
                    { ten: 'Đại Cường', danSo: 1, loai: 'Xã' },
                    { ten: 'Đại Hùng', danSo: 1, loai: 'Xã' },
                    { ten: 'Đội Bình', danSo: 1, loai: 'Xã' },
                    { ten: 'Đông Lỗ', danSo: 1, loai: 'Xã' },
                    { ten: 'Đồng Tiến', danSo: 1, loai: 'Xã' },
                    { ten: 'Đồng Tân', danSo: 1, loai: 'Xã' },
                    { ten: 'Hoa Sơn', danSo: 1, loai: 'Xã' },
                    { ten: 'Hòa Lâm', danSo: 1, loai: 'Xã' },
                    { ten: 'Hòa Nam', danSo: 1, loai: 'Xã' },
                    { ten: 'Hòa Phú', danSo: 1, loai: 'Xã' },
                    { ten: 'Hòa Xá', danSo: 1, loai: 'Xã' },
                    { ten: 'Hồng Quang', danSo: 1, loai: 'Xã' },
                    { ten: 'Kim Đường', danSo: 1, loai: 'Xã' },
                    { ten: 'Liên Bạt', danSo: 1, loai: 'Xã' },
                    { ten: 'Lưu Hoàng', danSo: 1, loai: 'Xã' },
                    { ten: 'Minh Đức', danSo: 1, loai: 'Xã' },
                    { ten: 'Phù Lưu', danSo: 1, loai: 'Xã' },
                    { ten: 'Phương Tú', danSo: 1, loai: 'Xã' },
                    { ten: 'Quảng Phú Cầu', danSo: 1, loai: 'Xã' },
                    { ten: 'Sơn Công', danSo: 1, loai: 'Xã' },
                    { ten: 'Tảo Dương Văn', danSo: 1, loai: 'Xã' },
                    { ten: 'Trầm Lộng', danSo: 1, loai: 'Xã' },
                    { ten: 'Trung Tú', danSo: 1, loai: 'Xã' },
                    { ten: 'Trường Thịnh', danSo: 1, loai: 'Xã' },
                    { ten: 'Vạn Thái', danSo: 1, loai: 'Xã' },
                    { ten: 'Viên An', danSo: 1, loai: 'Xã' },
                    { ten: 'Viên Nội', danSo: 1, loai: 'Xã' },
                ],
            },
        ],
    },
    {
        ten: 'Hồ Chí Minh',
        loai: 'Thành phố trực thuộc trung ương',
        danSo: 8993082,
        thanhPhan: [
            {
                ten: 'Quận 1',
                danSo: 142000,
                loai: 'Quận',
                thanhPhan: [
                    { ten: 'Bến Nghé', danSo: 1, loai: 'Phường' },
                    { ten: 'Bến Thành', danSo: 1, loai: 'Phường' },
                    { ten: 'Cô Giang', danSo: 1, loai: 'Phường' },
                    { ten: 'Cầu Kho', danSo: 1, loai: 'Phường' },
                    { ten: 'Cầu Ông Lãnh', danSo: 1, loai: 'Phường' },
                    { ten: 'Đa Kao', danSo: 1, loai: 'Phường' },
                    { ten: 'Nguyễn Cư Trinh', danSo: 1, loai: 'Phường' },
                    { ten: 'Nguyễn Thái Bình', danSo: 1, loai: 'Phường' },
                    { ten: 'Phạm Ngũ Lão', danSo: 1, loai: 'Phường' },
                    { ten: 'Tân Định', danSo: 1, loai: 'Phường' },
                ],
            },
            {
                ten: 'Quận 2',
                danSo: 180000,
                loai: 'Quận',
                thanhPhan: [
                    { ten: 'An Khánh', danSo: 1, loai: 'Phường' },
                    { ten: 'An Lợi Đông', danSo: 1, loai: 'Phường' },
                    { ten: 'An Phú', danSo: 1, loai: 'Phường' },
                    { ten: 'Bình An', danSo: 1, loai: 'Phường' },
                    { ten: 'Bình Khánh', danSo: 1, loai: 'Phường' },
                    { ten: 'Bình Trưng Đông', danSo: 1, loai: 'Phường' },
                    { ten: 'Bình Trưng Tây', danSo: 1, loai: 'Phường' },
                    { ten: 'Cát Lái', danSo: 1, loai: 'Phường' },
                    { ten: 'Thạnh Mỹ Lợi', danSo: 1, loai: 'Phường' },
                    { ten: 'Thảo Điền', danSo: 1, loai: 'Phường' },
                    { ten: 'Thủ Thiêm', danSo: 1, loai: 'Phường' },
                ],
            },
            {
                ten: 'Quận 3',
                danSo: 190000,
                loai: 'Quận',
                thanhPhan: [
                    { ten: '1', danSo: 1, loai: 'Phường' },
                    { ten: '2', danSo: 1, loai: 'Phường' },
                    { ten: '3', danSo: 1, loai: 'Phường' },
                    { ten: '4', danSo: 1, loai: 'Phường' },
                    { ten: '5', danSo: 1, loai: 'Phường' },
                    { ten: '6', danSo: 1, loai: 'Phường' },
                    { ten: '7', danSo: 1, loai: 'Phường' },
                    { ten: '8', danSo: 1, loai: 'Phường' },
                    { ten: '9', danSo: 1, loai: 'Phường' },
                    { ten: '10', danSo: 1, loai: 'Phường' },
                    { ten: '11', danSo: 1, loai: 'Phường' },
                    { ten: '12', danSo: 1, loai: 'Phường' },
                    { ten: '13', danSo: 1, loai: 'Phường' },
                    { ten: '14', danSo: 1, loai: 'Phường' },
                ],
            },
            {
                ten: 'Quận 4',
                danSo: 175000,
                loai: 'Quận',
                thanhPhan: [
                    { ten: '1', danSo: 1, loai: 'Phường' },
                    { ten: '2', danSo: 1, loai: 'Phường' },
                    { ten: '3', danSo: 1, loai: 'Phường' },
                    { ten: '4', danSo: 1, loai: 'Phường' },
                    { ten: '5', danSo: 1, loai: 'Phường' },
                    { ten: '6', danSo: 1, loai: 'Phường' },
                    { ten: '8', danSo: 1, loai: 'Phường' },
                    { ten: '9', danSo: 1, loai: 'Phường' },
                    { ten: '10', danSo: 1, loai: 'Phường' },
                    { ten: '12', danSo: 1, loai: 'Phường' },
                    { ten: '13', danSo: 1, loai: 'Phường' },
                    { ten: '14', danSo: 1, loai: 'Phường' },
                    { ten: '15', danSo: 1, loai: 'Phường' },
                    { ten: '16', danSo: 1, loai: 'Phường' },
                    { ten: '18', danSo: 1, loai: 'Phường' },
                ],
            },
            {
                ten: 'Quận 5',
                danSo: 159000,
                loai: 'Quận',
                thanhPhan: [
                    { ten: '1', danSo: 1, loai: 'Phường' },
                    { ten: '2', danSo: 1, loai: 'Phường' },
                    { ten: '3', danSo: 1, loai: 'Phường' },
                    { ten: '4', danSo: 1, loai: 'Phường' },
                    { ten: '5', danSo: 1, loai: 'Phường' },
                    { ten: '6', danSo: 1, loai: 'Phường' },
                    { ten: '8', danSo: 1, loai: 'Phường' },
                    { ten: '9', danSo: 1, loai: 'Phường' },
                    { ten: '10', danSo: 1, loai: 'Phường' },
                    { ten: '12', danSo: 1, loai: 'Phường' },
                    { ten: '13', danSo: 1, loai: 'Phường' },
                    { ten: '14', danSo: 1, loai: 'Phường' },
                    { ten: '15', danSo: 1, loai: 'Phường' },
                ],
            },
            {
                ten: 'Quận 6',
                danSo: 233000,
                loai: 'Quận',
                thanhPhan: [
                    { ten: '1', danSo: 1, loai: 'Phường' },
                    { ten: '2', danSo: 1, loai: 'Phường' },
                    { ten: '3', danSo: 1, loai: 'Phường' },
                    { ten: '4', danSo: 1, loai: 'Phường' },
                    { ten: '5', danSo: 1, loai: 'Phường' },
                    { ten: '6', danSo: 1, loai: 'Phường' },
                    { ten: '8', danSo: 1, loai: 'Phường' },
                    { ten: '9', danSo: 1, loai: 'Phường' },
                    { ten: '10', danSo: 1, loai: 'Phường' },
                    { ten: '12', danSo: 1, loai: 'Phường' },
                    { ten: '13', danSo: 1, loai: 'Phường' },
                    { ten: '14', danSo: 1, loai: 'Phường' },
                ],
            },
            {
                ten: 'Quận 7',
                danSo: 360000,
                loai: 'Quận',
                thanhPhan: [
                    { ten: 'Bình Thuận', danSo: 1, loai: 'Phường' },
                    { ten: 'Phú Mỹ', danSo: 1, loai: 'Phường' },
                    { ten: 'Phú Thuận', danSo: 1, loai: 'Phường' },
                    { ten: 'Tân Hưng', danSo: 1, loai: 'Phường' },
                    { ten: 'Tân Kiểng', danSo: 1, loai: 'Phường' },
                    { ten: 'Tân Phong', danSo: 1, loai: 'Phường' },
                    { ten: 'Tân Phú', danSo: 1, loai: 'Phường' },
                    { ten: 'Tân Quy', danSo: 1, loai: 'Phường' },
                    { ten: 'Tân Thuận Đông', danSo: 1, loai: 'Phường' },
                    { ten: 'Tân Thuận Tây', danSo: 1, loai: 'Phường' },
                ],
            },
            {
                ten: 'Quận 8',
                danSo: 424000,
                loai: 'Quận',
                thanhPhan: [
                    { ten: '1', danSo: 1, loai: 'Phường' },
                    { ten: '2', danSo: 1, loai: 'Phường' },
                    { ten: '3', danSo: 1, loai: 'Phường' },
                    { ten: '4', danSo: 1, loai: 'Phường' },
                    { ten: '5', danSo: 1, loai: 'Phường' },
                    { ten: '6', danSo: 1, loai: 'Phường' },
                    { ten: '8', danSo: 1, loai: 'Phường' },
                    { ten: '9', danSo: 1, loai: 'Phường' },
                    { ten: '10', danSo: 1, loai: 'Phường' },
                    { ten: '12', danSo: 1, loai: 'Phường' },
                    { ten: '13', danSo: 1, loai: 'Phường' },
                    { ten: '14', danSo: 1, loai: 'Phường' },
                    { ten: '15', danSo: 1, loai: 'Phường' },
                    { ten: '16', danSo: 1, loai: 'Phường' },
                ],
            },
            {
                ten: 'Quận 9',
                danSo: 397000,
                loai: 'Quận',
                thanhPhan: [
                    { ten: 'Hiệp Phú', danSo: 1, loai: 'Phường' },
                    { ten: 'Long Bình', danSo: 1, loai: 'Phường' },
                    { ten: 'Long Phước', danSo: 1, loai: 'Phường' },
                    { ten: 'Long Thạnh Mỹ', danSo: 1, loai: 'Phường' },
                    { ten: 'Long Trường', danSo: 1, loai: 'Phường' },
                    { ten: 'Phú Hữu', danSo: 1, loai: 'Phường' },
                    { ten: 'Phước Bình', danSo: 1, loai: 'Phường' },
                    { ten: 'Phước Long A', danSo: 1, loai: 'Phường' },
                    { ten: 'Phước Long B', danSo: 1, loai: 'Phường' },
                    { ten: 'Tân Phú', danSo: 1, loai: 'Phường' },
                    { ten: 'Tăng Nhơn Phú A', danSo: 1, loai: 'Phường' },
                    { ten: 'Tăng Nhơn Phú B', danSo: 1, loai: 'Phường' },
                    { ten: 'Trường Thạnh', danSo: 1, loai: 'Phường' },
                ],
            },
            {
                ten: 'Quận 10',
                danSo: 234000,
                loai: 'Quận',
                thanhPhan: [
                    { ten: '1', danSo: 1, loai: 'Phường' },
                    { ten: '2', danSo: 1, loai: 'Phường' },
                    { ten: '3', danSo: 1, loai: 'Phường' },
                    { ten: '4', danSo: 1, loai: 'Phường' },
                    { ten: '5', danSo: 1, loai: 'Phường' },
                    { ten: '6', danSo: 1, loai: 'Phường' },
                    { ten: '8', danSo: 1, loai: 'Phường' },
                    { ten: '9', danSo: 1, loai: 'Phường' },
                    { ten: '10', danSo: 1, loai: 'Phường' },
                    { ten: '12', danSo: 1, loai: 'Phường' },
                    { ten: '13', danSo: 1, loai: 'Phường' },
                    { ten: '14', danSo: 1, loai: 'Phường' },
                    { ten: '15', danSo: 1, loai: 'Phường' },
                ],
            },
            {
                ten: 'Quận 11',
                danSo: 209000,
                loai: 'Quận',
                thanhPhan: [
                    { ten: '1', danSo: 1, loai: 'Phường' },
                    { ten: '2', danSo: 1, loai: 'Phường' },
                    { ten: '3', danSo: 1, loai: 'Phường' },
                    { ten: '4', danSo: 1, loai: 'Phường' },
                    { ten: '5', danSo: 1, loai: 'Phường' },
                    { ten: '6', danSo: 1, loai: 'Phường' },
                    { ten: '8', danSo: 1, loai: 'Phường' },
                    { ten: '9', danSo: 1, loai: 'Phường' },
                    { ten: '10', danSo: 1, loai: 'Phường' },
                    { ten: '12', danSo: 1, loai: 'Phường' },
                    { ten: '13', danSo: 1, loai: 'Phường' },
                    { ten: '14', danSo: 1, loai: 'Phường' },
                    { ten: '15', danSo: 1, loai: 'Phường' },
                    { ten: '16', danSo: 1, loai: 'Phường' },
                ],
            },
            {
                ten: 'Quận 12',
                danSo: 620000,
                loai: 'Quận',
                thanhPhan: [
                    { ten: 'An Phú Đông', danSo: 1, loai: 'Phường' },
                    { ten: 'Đông Hưng Thuận', danSo: 1, loai: 'Phường' },
                    { ten: 'Hiệp Thành', danSo: 1, loai: 'Phường' },
                    { ten: 'Tân Chánh Hiệp', danSo: 1, loai: 'Phường' },
                    { ten: 'Tân Hưng Thuận', danSo: 1, loai: 'Phường' },
                    { ten: 'Tân Thới Hiệp', danSo: 1, loai: 'Phường' },
                    { ten: 'Tân Thới Nhất', danSo: 1, loai: 'Phường' },
                    { ten: 'Thạnh Lộc', danSo: 1, loai: 'Phường' },
                    { ten: 'Thạnh Xuân', danSo: 1, loai: 'Phường' },
                    { ten: 'Thới An', danSo: 1, loai: 'Phường' },
                    { ten: 'Trung Mỹ Tây', danSo: 1, loai: 'Phường' },
                ],
            },
            {
                ten: 'Bình Tân',
                danSo: 784000,
                loai: 'Quận',
                thanhPhan: [
                    { ten: 'An Lạc', danSo: 1, loai: 'Phường' },
                    { ten: 'An Lạc A', danSo: 1, loai: 'Phường' },
                    { ten: 'Bình Hưng Hòa', danSo: 1, loai: 'Phường' },
                    { ten: 'Bình Hưng Hòa A', danSo: 1, loai: 'Phường' },
                    { ten: 'Bình Hưng Hòa B', danSo: 1, loai: 'Phường' },
                    { ten: 'Bình Trị Đông', danSo: 1, loai: 'Phường' },
                    { ten: 'Bình Trị Đông A', danSo: 1, loai: 'Phường' },
                    { ten: 'Bình Trị Đông B', danSo: 1, loai: 'Phường' },
                    { ten: 'Tân Tạo', danSo: 1, loai: 'Phường' },
                    { ten: 'Tân Tạo A', danSo: 1, loai: 'Phường' },
                ],
            },
            {
                ten: 'Bình Thạnh',
                danSo: 499000,
                loai: 'Quận',
                thanhPhan: [
                    { ten: '1', danSo: 1, loai: 'Phường' },
                    { ten: '2', danSo: 1, loai: 'Phường' },
                    { ten: '3', danSo: 1, loai: 'Phường' },
                    { ten: '5', danSo: 1, loai: 'Phường' },
                    { ten: '6', danSo: 1, loai: 'Phường' },
                    { ten: '7', danSo: 1, loai: 'Phường' },
                    { ten: '11', danSo: 1, loai: 'Phường' },
                    { ten: '12', danSo: 1, loai: 'Phường' },
                    { ten: '13', danSo: 1, loai: 'Phường' },
                    { ten: '14', danSo: 1, loai: 'Phường' },
                    { ten: '15', danSo: 1, loai: 'Phường' },
                    { ten: '17', danSo: 1, loai: 'Phường' },
                    { ten: '19', danSo: 1, loai: 'Phường' },
                    { ten: '21', danSo: 1, loai: 'Phường' },
                    { ten: '22', danSo: 1, loai: 'Phường' },
                    { ten: '24', danSo: 1, loai: 'Phường' },
                    { ten: '25', danSo: 1, loai: 'Phường' },
                    { ten: '26', danSo: 1, loai: 'Phường' },
                    { ten: '27', danSo: 1, loai: 'Phường' },
                    { ten: '28', danSo: 1, loai: 'Phường' },
                ],
            },
            {
                ten: 'Gò Vấp',
                danSo: 676000,
                loai: 'Quận',
                thanhPhan: [
                    { ten: '1', danSo: 1, loai: 'Phường' },
                    { ten: '3', danSo: 1, loai: 'Phường' },
                    { ten: '4', danSo: 1, loai: 'Phường' },
                    { ten: '5', danSo: 1, loai: 'Phường' },
                    { ten: '6', danSo: 1, loai: 'Phường' },
                    { ten: '7', danSo: 1, loai: 'Phường' },
                    { ten: '8', danSo: 1, loai: 'Phường' },
                    { ten: '9', danSo: 1, loai: 'Phường' },
                    { ten: '10', danSo: 1, loai: 'Phường' },
                    { ten: '11', danSo: 1, loai: 'Phường' },
                    { ten: '12', danSo: 1, loai: 'Phường' },
                    { ten: '13', danSo: 1, loai: 'Phường' },
                    { ten: '14', danSo: 1, loai: 'Phường' },
                    { ten: '15', danSo: 1, loai: 'Phường' },
                    { ten: '16', danSo: 1, loai: 'Phường' },
                    { ten: '17', danSo: 1, loai: 'Phường' },
                ],
            },
            {
                ten: 'Phú Nhuận',
                danSo: 163000,
                loai: 'Quận',
                thanhPhan: [
                    { ten: '1', danSo: 1, loai: 'Phường' },
                    { ten: '2', danSo: 1, loai: 'Phường' },
                    { ten: '3', danSo: 1, loai: 'Phường' },
                    { ten: '4', danSo: 1, loai: 'Phường' },
                    { ten: '5', danSo: 1, loai: 'Phường' },
                    { ten: '7', danSo: 1, loai: 'Phường' },
                    { ten: '8', danSo: 1, loai: 'Phường' },
                    { ten: '9', danSo: 1, loai: 'Phường' },
                    { ten: '10', danSo: 1, loai: 'Phường' },
                    { ten: '11', danSo: 1, loai: 'Phường' },
                    { ten: '12', danSo: 1, loai: 'Phường' },
                    { ten: '13', danSo: 1, loai: 'Phường' },
                    { ten: '14', danSo: 1, loai: 'Phường' },
                    { ten: '15', danSo: 1, loai: 'Phường' },
                    { ten: '17', danSo: 1, loai: 'Phường' },
                ],
            },
            {
                ten: 'Tân Bình',
                danSo: 474000,
                loai: 'Quận',
                thanhPhan: [
                    { ten: '1', danSo: 1, loai: 'Phường' },
                    { ten: '2', danSo: 1, loai: 'Phường' },
                    { ten: '3', danSo: 1, loai: 'Phường' },
                    { ten: '4', danSo: 1, loai: 'Phường' },
                    { ten: '5', danSo: 1, loai: 'Phường' },
                    { ten: '6', danSo: 1, loai: 'Phường' },
                    { ten: '8', danSo: 1, loai: 'Phường' },
                    { ten: '9', danSo: 1, loai: 'Phường' },
                    { ten: '10', danSo: 1, loai: 'Phường' },
                    { ten: '12', danSo: 1, loai: 'Phường' },
                    { ten: '13', danSo: 1, loai: 'Phường' },
                    { ten: '14', danSo: 1, loai: 'Phường' },
                    { ten: '15', danSo: 1, loai: 'Phường' },
                ],
            },
            {
                ten: 'Tân Phú',
                danSo: 485000,
                loai: 'Quận',
                thanhPhan: [
                    { ten: 'Hiệp Tân', danSo: 1, loai: 'Phường' },
                    { ten: 'Hòa Thạnh', danSo: 1, loai: 'Phường' },
                    { ten: 'Phú Thạnh', danSo: 1, loai: 'Phường' },
                    { ten: 'Phú Thọ Hòa', danSo: 1, loai: 'Phường' },
                    { ten: 'Phú Trung', danSo: 1, loai: 'Phường' },
                    { ten: 'Sơn Kỳ', danSo: 1, loai: 'Phường' },
                    { ten: 'Tân Quý', danSo: 1, loai: 'Phường' },
                    { ten: 'Tân Sơn Nhì', danSo: 1, loai: 'Phường' },
                    { ten: 'Tân Thành', danSo: 1, loai: 'Phường' },
                    { ten: 'Tân Thới Hòa', danSo: 1, loai: 'Phường' },
                    { ten: 'Tây Thạnh', danSo: 1, loai: 'Phường' },
                ],
            },
            {
                ten: 'Thủ Đức',
                danSo: 592000,
                loai: 'Quận',
                thanhPhan: [
                    { ten: 'Bình Chiểu', danSo: 1, loai: 'Phường' },
                    { ten: 'Bình Thọ', danSo: 1, loai: 'Phường' },
                    { ten: 'Hiệp Bình Chánh', danSo: 1, loai: 'Phường' },
                    { ten: 'Hiệp Bình Phước', danSo: 1, loai: 'Phường' },
                    { ten: 'Linh Chiểu', danSo: 1, loai: 'Phường' },
                    { ten: 'Linh Đông', danSo: 1, loai: 'Phường' },
                    { ten: 'Linh Tây', danSo: 1, loai: 'Phường' },
                    { ten: 'Linh Trung', danSo: 1, loai: 'Phường' },
                    { ten: 'Linh Xuân', danSo: 1, loai: 'Phường' },
                    { ten: 'Tam Bình', danSo: 1, loai: 'Phường' },
                    { ten: 'Tam Phú', danSo: 1, loai: 'Phường' },
                    { ten: 'Trường Thọ', danSo: 1, loai: 'Phường' },
                ],
            },
            {
                ten: 'Bình Chánh',
                danSo: 705000,
                loai: 'Huyện',
                thanhPhan: [
                    { ten: 'Tân Túc', danSo: 1, loai: 'Thị trấn' },
                    { ten: 'An Phú Tây', danSo: 1, loai: 'Xã' },
                    { ten: 'Bình Chánh', danSo: 1, loai: 'Xã' },
                    { ten: 'Bình Hưng', danSo: 1, loai: 'Xã' },
                    { ten: 'Bình Lợi', danSo: 1, loai: 'Xã' },
                    { ten: 'Đa Phước', danSo: 1, loai: 'Xã' },
                    { ten: 'Hưng Long', danSo: 1, loai: 'Xã' },
                    { ten: 'Lê Minh Xuân', danSo: 1, loai: 'Xã' },
                    { ten: 'Phạm Văn Hai', danSo: 1, loai: 'Xã' },
                    { ten: 'Phong Phú', danSo: 1, loai: 'Xã' },
                    { ten: 'Quy Đức', danSo: 1, loai: 'Xã' },
                    { ten: 'Tân Kiên', danSo: 1, loai: 'Xã' },
                    { ten: 'Tân Nhựt', danSo: 1, loai: 'Xã' },
                    { ten: 'Tân Quý Tây', danSo: 1, loai: 'Xã' },
                    { ten: 'Vĩnh Lộc A', danSo: 1, loai: 'Xã' },
                    { ten: 'Vĩnh Lộc B', danSo: 1, loai: 'Xã' },
                ],
            },
            {
                ten: 'Cần Giờ',
                danSo: 71000,
                loai: 'Huyện',
                thanhPhan: [
                    { ten: 'Cần Thạnh', danSo: 1, loai: 'Thị trấn' },
                    { ten: 'An Thới Đông', danSo: 1, loai: 'Xã' },
                    { ten: 'Bình Khánh', danSo: 1, loai: 'Xã' },
                    { ten: 'Long Hòa', danSo: 1, loai: 'Xã' },
                    { ten: 'Lý Nhơn', danSo: 1, loai: 'Xã' },
                    { ten: 'Tam Thôn Hiệp', danSo: 1, loai: 'Xã' },
                    { ten: 'Thạnh An', danSo: 1, loai: 'Xã' },
                ],
            },
            {
                ten: 'Củ Chi',
                danSo: 462000,
                loai: 'Huyện',
                thanhPhan: [
                    { ten: 'Củ Chi', danSo: 1, loai: 'Thị trấn' },
                    { ten: 'An Nhơn Tây', danSo: 1, loai: 'Xã' },
                    { ten: 'An Phú', danSo: 1, loai: 'Xã' },
                    { ten: 'Bình Mỹ', danSo: 1, loai: 'Xã' },
                    { ten: 'Hòa Phú', danSo: 1, loai: 'Xã' },
                    { ten: 'Nhuận Đức', danSo: 1, loai: 'Xã' },
                    { ten: 'Phạm Văn Cội', danSo: 1, loai: 'Xã' },
                    { ten: 'Phú Hòa Đông', danSo: 1, loai: 'Xã' },
                    { ten: 'Phú Mỹ Hưng', danSo: 1, loai: 'Xã' },
                    { ten: 'Phước Hiệp', danSo: 1, loai: 'Xã' },
                    { ten: 'Phước Thạnh', danSo: 1, loai: 'Xã' },
                    { ten: 'Phước Vĩnh An', danSo: 1, loai: 'Xã' },
                    { ten: 'Tân An Hội', danSo: 1, loai: 'Xã' },
                    { ten: 'Tân Phú Trung', danSo: 1, loai: 'Xã' },
                    { ten: 'Tân Thạnh Đông', danSo: 1, loai: 'Xã' },
                    { ten: 'Tân Thạnh Tây', danSo: 1, loai: 'Xã' },
                    { ten: 'Tân Thông Hội', danSo: 1, loai: 'Xã' },
                    { ten: 'Thái Mỹ', danSo: 1, loai: 'Xã' },
                    { ten: 'Trung An', danSo: 1, loai: 'Xã' },
                    { ten: 'Trung Lập Hạ', danSo: 1, loai: 'Xã' },
                    { ten: 'Trung Lập Thượng', danSo: 1, loai: 'Xã' },
                ],
            },
            {
                ten: 'Hóc Môn',
                danSo: 542000,
                loai: 'Huyện',
                thanhPhan: [
                    { ten: 'Hóc Môn', danSo: 1, loai: 'Thị trấn' },
                    { ten: 'Bà Điểm', danSo: 1, loai: 'Xã' },
                    { ten: 'Đông Thạnh', danSo: 1, loai: 'Xã' },
                    { ten: 'Nhị Bình', danSo: 1, loai: 'Xã' },
                    { ten: 'Tân Hiệp', danSo: 1, loai: 'Xã' },
                    { ten: 'Tân Thới Nhì', danSo: 1, loai: 'Xã' },
                    { ten: 'Tân Xuân', danSo: 1, loai: 'Xã' },
                    { ten: 'Thới Tam Thôn', danSo: 1, loai: 'Xã' },
                    { ten: 'Trung Chánh', danSo: 1, loai: 'Xã' },
                    { ten: 'Xuân Thới Đông', danSo: 1, loai: 'Xã' },
                    { ten: 'Xuân Thới Sơn', danSo: 1, loai: 'Xã' },
                    { ten: 'Xuân Thới Thượng', danSo: 1, loai: 'Xã' },
                ],
            },
            {
                ten: 'Nhà Bè',
                danSo: 206000,
                loai: 'Huyện',
                thanhPhan: [
                    { ten: 'Nhà Bè', danSo: 1, loai: 'Thị trấn' },
                    { ten: 'Hiệp Phước', danSo: 1, loai: 'Xã' },
                    { ten: 'Long Thới', danSo: 1, loai: 'Xã' },
                    { ten: 'Nhơn Đức', danSo: 1, loai: 'Xã' },
                    { ten: 'Phú Xuân', danSo: 1, loai: 'Xã' },
                    { ten: 'Phước Kiển', danSo: 1, loai: 'Xã' },
                    { ten: 'Phước Lộc', danSo: 1, loai: 'Xã' },
                ],
            },
        ],
    },
    {
        ten: 'Hải Phòng',
        loai: 'Thành phố trực thuộc trung ương',
        danSo: 2028514,
        thanhPhan: [
            {
                ten: 'Đồ Sơn',
                danSo: 49029,
                loai: 'Quận',
                thanhPhan: [
                    { ten: 'Bàng La', danSo: 1, loai: 'Phường' },
                    { ten: 'Hải Sơn', danSo: 1, loai: 'Phường' },
                    { ten: 'Hợp Đức', danSo: 1, loai: 'Phường' },
                    { ten: 'Minh Đức', danSo: 1, loai: 'Phường' },
                    { ten: 'Ngọc Xuyên', danSo: 1, loai: 'Phường' },
                    { ten: 'Vạn Hương', danSo: 1, loai: 'Phường' },
                ],
            },
            {
                ten: 'Dương Kinh',
                danSo: 60319,
                loai: 'Quận',
                thanhPhan: [
                    { ten: 'Anh Dũng', danSo: 1, loai: 'Phường' },
                    { ten: 'Đa Phúc', danSo: 1, loai: 'Phường' },
                    { ten: 'Hải Thành', danSo: 1, loai: 'Phường' },
                    { ten: 'Hòa Nghĩa', danSo: 1, loai: 'Phường' },
                    { ten: 'Hưng Đạo', danSo: 1, loai: 'Phường' },
                    { ten: 'Tân Thành', danSo: 1, loai: 'Phường' },
                ],
            },
            {
                ten: 'Hải An',
                danSo: 132943,
                loai: 'Quận',
                thanhPhan: [
                    { ten: 'Cát Bi', danSo: 1, loai: 'Phường' },
                    { ten: 'Đằng Lâm', danSo: 1, loai: 'Phường' },
                    { ten: 'Đằng Hải', danSo: 1, loai: 'Phường' },
                    { ten: 'Đông Hải 1', danSo: 1, loai: 'Phường' },
                    { ten: 'Đông Hải 2', danSo: 1, loai: 'Phường' },
                    { ten: 'Nam Hải', danSo: 1, loai: 'Phường' },
                    { ten: 'Thành Tô', danSo: 1, loai: 'Phường' },
                    { ten: 'Tràng Cát', danSo: 1, loai: 'Phường' },
                ],
            },
            {
                ten: 'Hồng Bàng',
                danSo: 96111,
                loai: 'Quận',
                thanhPhan: [
                    { ten: 'Hạ Lý', danSo: 1, loai: 'Phường' },
                    { ten: 'Hoàng Văn Thụ', danSo: 1, loai: 'Phường' },
                    { ten: 'Hùng Vương', danSo: 1, loai: 'Phường' },
                    { ten: 'Minh Khai', danSo: 1, loai: 'Phường' },
                    { ten: 'Phan Bội Châu', danSo: 1, loai: 'Phường' },
                    { ten: 'Quán Toan', danSo: 1, loai: 'Phường' },
                    { ten: 'Sở Dầu', danSo: 1, loai: 'Phường' },
                    { ten: 'Thượng Lý', danSo: 1, loai: 'Phường' },
                    { ten: 'Trại Chuối', danSo: 1, loai: 'Phường' },
                ],
            },
            {
                ten: 'Kiến An',
                danSo: 118047,
                loai: 'Quận',
                thanhPhan: [
                    { ten: 'Bắc Sơn', danSo: 1, loai: 'Phường' },
                    { ten: 'Đồng Hòa', danSo: 1, loai: 'Phường' },
                    { ten: 'Lãm Hà', danSo: 1, loai: 'Phường' },
                    { ten: 'Nam Sơn', danSo: 1, loai: 'Phường' },
                    { ten: 'Ngọc Sơn', danSo: 1, loai: 'Phường' },
                    { ten: 'Phù Liễn', danSo: 1, loai: 'Phường' },
                    { ten: 'Quán Trữ', danSo: 1, loai: 'Phường' },
                    { ten: 'Trần Thành Ngọ', danSo: 1, loai: 'Phường' },
                    { ten: 'Tràng Minh', danSo: 1, loai: 'Phường' },
                    { ten: 'Văn Đẩu', danSo: 1, loai: 'Phường' },
                ],
            },
            {
                ten: 'Lê Chân',
                danSo: 219762,
                loai: 'Quận',
                thanhPhan: [
                    { ten: 'An Biên', danSo: 1, loai: 'Phường' },
                    { ten: 'An Dương', danSo: 1, loai: 'Phường' },
                    { ten: 'Cát Dài', danSo: 1, loai: 'Phường' },
                    { ten: 'Đông Hải', danSo: 1, loai: 'Phường' },
                    { ten: 'Dư Hàng', danSo: 1, loai: 'Phường' },
                    { ten: 'Dư Hàng Kênh', danSo: 1, loai: 'Phường' },
                    { ten: 'Hàng Kênh', danSo: 1, loai: 'Phường' },
                    { ten: 'Hồ Nam', danSo: 1, loai: 'Phường' },
                    { ten: 'Kênh Dương', danSo: 1, loai: 'Phường' },
                    { ten: 'Lam Sơn', danSo: 1, loai: 'Phường' },
                    { ten: 'Nghĩa Xá', danSo: 1, loai: 'Phường' },
                    { ten: 'Niệm Nghĩa', danSo: 1, loai: 'Phường' },
                    { ten: 'Trại Cau', danSo: 1, loai: 'Phường' },
                    { ten: 'Trần Nguyên Hãn', danSo: 1, loai: 'Phường' },
                    { ten: 'Vĩnh Niệm', danSo: 1, loai: 'Phường' },
                ],
            },
            {
                ten: 'Ngô Quyền',
                danSo: 165309,
                loai: 'Quận',
                thanhPhan: [
                    { ten: 'Cầu Đất', danSo: 1, loai: 'Phường' },
                    { ten: 'Cầu Tre', danSo: 1, loai: 'Phường' },
                    { ten: 'Đằng Giang', danSo: 1, loai: 'Phường' },
                    { ten: 'Đông Khê', danSo: 1, loai: 'Phường' },
                    { ten: 'Đồng Quốc Bình', danSo: 1, loai: 'Phường' },
                    { ten: 'Gia Viên', danSo: 1, loai: 'Phường' },
                    { ten: 'Lạc Viên', danSo: 1, loai: 'Phường' },
                    { ten: 'Lạch Tray', danSo: 1, loai: 'Phường' },
                    { ten: 'Lê Lợi', danSo: 1, loai: 'Phường' },
                    { ten: 'Máy Chai', danSo: 1, loai: 'Phường' },
                    { ten: 'Máy Tơ', danSo: 1, loai: 'Phường' },
                    { ten: 'Vạn Mỹ', danSo: 1, loai: 'Phường' },
                ],
            },
            {
                ten: 'An Dương',
                danSo: 195717,
                loai: 'Huyện',
                thanhPhan: [
                    { ten: 'An Dương', danSo: 1, loai: 'Thị trấn' },
                    { ten: 'An Đồng', danSo: 1, loai: 'Xã' },
                    { ten: 'An Hòa', danSo: 1, loai: 'Xã' },
                    { ten: 'An Hồng', danSo: 1, loai: 'Xã' },
                    { ten: 'An Hưng', danSo: 1, loai: 'Xã' },
                    { ten: 'Bắc Sơn', danSo: 1, loai: 'Xã' },
                    { ten: 'Đại Bản', danSo: 1, loai: 'Xã' },
                    { ten: 'Đặng Cương', danSo: 1, loai: 'Xã' },
                    { ten: 'Đồng Thái', danSo: 1, loai: 'Xã' },
                    { ten: 'Hồng Phong', danSo: 1, loai: 'Xã' },
                    { ten: 'Hồng Thái', danSo: 1, loai: 'Xã' },
                    { ten: 'Lê Lợi', danSo: 1, loai: 'Xã' },
                    { ten: 'Lê Thiện', danSo: 1, loai: 'Xã' },
                    { ten: 'Nam Sơn', danSo: 1, loai: 'Xã' },
                    { ten: 'Quốc Tuấn', danSo: 1, loai: 'Xã' },
                    { ten: 'Tân Tiến', danSo: 1, loai: 'Xã' },
                ],
            },
            {
                ten: 'An Lão',
                danSo: 146712,
                loai: 'Huyện',
                thanhPhan: [
                    { ten: 'An Lão', danSo: 1, loai: 'Thị trấn' },
                    { ten: 'Trường Sơn', danSo: 1, loai: 'Xã' },
                    { ten: 'An Thái', danSo: 1, loai: 'Xã' },
                    { ten: 'An Thắng', danSo: 1, loai: 'Xã' },
                    { ten: 'An Thọ', danSo: 1, loai: 'Xã' },
                    { ten: 'An Tiến', danSo: 1, loai: 'Xã' },
                    { ten: 'Bát Trang', danSo: 1, loai: 'Xã' },
                    { ten: 'Chiến Thắng', danSo: 1, loai: 'Xã' },
                    { ten: 'Mỹ Đức', danSo: 1, loai: 'Xã' },
                    { ten: 'Quang Hưng', danSo: 1, loai: 'Xã' },
                    { ten: 'Quang Trung', danSo: 1, loai: 'Xã' },
                    { ten: 'Quốc Tuấn', danSo: 1, loai: 'Xã' },
                    { ten: 'Tân Dân', danSo: 1, loai: 'Xã' },
                    { ten: 'Tân Viên', danSo: 1, loai: 'Xã' },
                    { ten: 'Thái Sơn', danSo: 1, loai: 'Xã' },
                    { ten: 'Trường Thành', danSo: 1, loai: 'Xã' },
                    { ten: 'Trường Thọ', danSo: 1, loai: 'Xã' },
                ],
            },
            { ten: 'Bạch Long Vĩ', danSo: 624, loai: 'Huyện', thanhPhan: [] },
            {
                ten: 'Cát Hải',
                danSo: 32090,
                loai: 'Huyện',
                thanhPhan: [
                    { ten: 'Cát Bà', danSo: 1, loai: 'Thị trấn' },
                    { ten: 'Cát Hải', danSo: 1, loai: 'Thị trấn' },
                    { ten: 'Đồng Bài', danSo: 1, loai: 'Xã' },
                    { ten: 'Gia Luận', danSo: 1, loai: 'Xã' },
                    { ten: 'Hiền Hào', danSo: 1, loai: 'Xã' },
                    { ten: 'Hoàng Châu', danSo: 1, loai: 'Xã' },
                    { ten: 'Nghĩa Lộ', danSo: 1, loai: 'Xã' },
                    { ten: 'Phù Long', danSo: 1, loai: 'Xã' },
                    { ten: 'Trân Châu', danSo: 1, loai: 'Xã' },
                    { ten: 'Văn Phong', danSo: 1, loai: 'Xã' },
                    { ten: 'Việt Hải', danSo: 1, loai: 'Xã' },
                    { ten: 'Xuân Đám', danSo: 1, loai: 'Xã' },
                ],
            },
            {
                ten: 'Kiến Thụy',
                danSo: 140417,
                loai: 'Huyện',
                thanhPhan: [
                    { ten: 'Núi Đối', danSo: 1, loai: 'Thị trấn' },
                    { ten: 'Đại Đồng', danSo: 1, loai: 'Xã' },
                    { ten: 'Đại Hà', danSo: 1, loai: 'Xã' },
                    { ten: 'Đại Hợp', danSo: 1, loai: 'Xã' },
                    { ten: 'Đoàn Xá', danSo: 1, loai: 'Xã' },
                    { ten: 'Đông Phương', danSo: 1, loai: 'Xã' },
                    { ten: 'Du Lễ', danSo: 1, loai: 'Xã' },
                    { ten: 'Hữu Bằng', danSo: 1, loai: 'Xã' },
                    { ten: 'Kiến Quốc', danSo: 1, loai: 'Xã' },
                    { ten: 'Minh Tân', danSo: 1, loai: 'Xã' },
                    { ten: 'Ngũ Đoan', danSo: 1, loai: 'Xã' },
                    { ten: 'Ngũ Phúc', danSo: 1, loai: 'Xã' },
                    { ten: 'Tân Phong', danSo: 1, loai: 'Xã' },
                    { ten: 'Tân Trào', danSo: 1, loai: 'Xã' },
                    { ten: 'Thanh Sơn', danSo: 1, loai: 'Xã' },
                    { ten: 'Thuận Thiên', danSo: 1, loai: 'Xã' },
                    { ten: 'Thụy Hương', danSo: 1, loai: 'Xã' },
                    { ten: 'Tú Sơn', danSo: 1, loai: 'Xã' },
                ],
            },
            {
                ten: 'Thủy Nguyên',
                danSo: 333810,
                loai: 'Huyện',
                thanhPhan: [
                    { ten: 'Núi Đèo', danSo: 1, loai: 'Thị trấn' },
                    { ten: 'Minh Đức', danSo: 1, loai: 'Xã' },
                    { ten: 'An Lư', danSo: 1, loai: 'Xã' },
                    { ten: 'An Sơn', danSo: 1, loai: 'Xã' },
                    { ten: 'Cao Nhân', danSo: 1, loai: 'Xã' },
                    { ten: 'Chính Mỹ', danSo: 1, loai: 'Xã' },
                    { ten: 'Dương Quan', danSo: 1, loai: 'Xã' },
                    { ten: 'Đông Sơn', danSo: 1, loai: 'Xã' },
                    { ten: 'Gia Đức', danSo: 1, loai: 'Xã' },
                    { ten: 'Gia Minh', danSo: 1, loai: 'Xã' },
                    { ten: 'Hoa Động', danSo: 1, loai: 'Xã' },
                    { ten: 'Hòa Bình', danSo: 1, loai: 'Xã' },
                    { ten: 'Hoàng Động', danSo: 1, loai: 'Xã' },
                    { ten: 'Hợp Thành', danSo: 1, loai: 'Xã' },
                    { ten: 'Kênh Giang', danSo: 1, loai: 'Xã' },
                    { ten: 'Kiền Bái', danSo: 1, loai: 'Xã' },
                    { ten: 'Kỳ Sơn', danSo: 1, loai: 'Xã' },
                    { ten: 'Lại Xuân', danSo: 1, loai: 'Xã' },
                    { ten: 'Lâm Động', danSo: 1, loai: 'Xã' },
                    { ten: 'Lập Lễ', danSo: 1, loai: 'Xã' },
                    { ten: 'Liên Khê', danSo: 1, loai: 'Xã' },
                    { ten: 'Lưu Kiếm', danSo: 1, loai: 'Xã' },
                    { ten: 'Lưu Kỳ', danSo: 1, loai: 'Xã' },
                    { ten: 'Minh Tân', danSo: 1, loai: 'Xã' },
                    { ten: 'Mỹ Đồng', danSo: 1, loai: 'Xã' },
                    { ten: 'Ngũ Lão', danSo: 1, loai: 'Xã' },
                    { ten: 'Phả Lễ', danSo: 1, loai: 'Xã' },
                    { ten: 'Phù Ninh', danSo: 1, loai: 'Xã' },
                    { ten: 'Phục Lễ', danSo: 1, loai: 'Xã' },
                    { ten: 'Quảng Thanh', danSo: 1, loai: 'Xã' },
                    { ten: 'Tam Hưng', danSo: 1, loai: 'Xã' },
                    { ten: 'Tân Dương', danSo: 1, loai: 'Xã' },
                    { ten: 'Thiên Hương', danSo: 1, loai: 'Xã' },
                    { ten: 'Thủy Đường', danSo: 1, loai: 'Xã' },
                    { ten: 'Thủy Sơn', danSo: 1, loai: 'Xã' },
                    { ten: 'Thủy Triều', danSo: 1, loai: 'Xã' },
                    { ten: 'Trung Hà', danSo: 1, loai: 'Xã' },
                ],
            },
            {
                ten: 'Tiên Lãng',
                danSo: 154789,
                loai: 'Huyện',
                thanhPhan: [
                    { ten: 'Tiên Lãng', danSo: 1, loai: 'Thị trấn' },
                    { ten: 'Bắc Hưng', danSo: 1, loai: 'Xã' },
                    { ten: 'Bạch Đằng', danSo: 1, loai: 'Xã' },
                    { ten: 'Cấp Tiến', danSo: 1, loai: 'Xã' },
                    { ten: 'Đại Thắng', danSo: 1, loai: 'Xã' },
                    { ten: 'Đoàn Lập', danSo: 1, loai: 'Xã' },
                    { ten: 'Đông Hưng', danSo: 1, loai: 'Xã' },
                    { ten: 'Hùng Thắng', danSo: 1, loai: 'Xã' },
                    { ten: 'Khởi Nghĩa', danSo: 1, loai: 'Xã' },
                    { ten: 'Kiến Thiết', danSo: 1, loai: 'Xã' },
                    { ten: 'Nam Hưng', danSo: 1, loai: 'Xã' },
                    { ten: 'Quang Phục', danSo: 1, loai: 'Xã' },
                    { ten: 'Quyết Tiến', danSo: 1, loai: 'Xã' },
                    { ten: 'Tây Hưng', danSo: 1, loai: 'Xã' },
                    { ten: 'Tiên Cường', danSo: 1, loai: 'Xã' },
                    { ten: 'Tiên Minh', danSo: 1, loai: 'Xã' },
                    { ten: 'Tiên Thắng', danSo: 1, loai: 'Xã' },
                    { ten: 'Tiên Thanh', danSo: 1, loai: 'Xã' },
                    { ten: 'Toàn Thắng', danSo: 1, loai: 'Xã' },
                    { ten: 'Tự Cường', danSo: 1, loai: 'Xã' },
                    { ten: 'Vinh Quang', danSo: 1, loai: 'Xã' },
                ],
            },
            {
                ten: 'Vĩnh Bảo',
                danSo: 182835,
                loai: 'Huyện',
                thanhPhan: [
                    { ten: 'Vĩnh Bảo', danSo: 1, loai: 'Thị trấn' },
                    { ten: 'An Hòa', danSo: 1, loai: 'Xã' },
                    { ten: 'Cao Minh', danSo: 1, loai: 'Xã' },
                    { ten: 'Cổ Am', danSo: 1, loai: 'Xã' },
                    { ten: 'Cộng Hiền', danSo: 1, loai: 'Xã' },
                    { ten: 'Đồng Minh', danSo: 1, loai: 'Xã' },
                    { ten: 'Dũng Tiến', danSo: 1, loai: 'Xã' },
                    { ten: 'Giang Biên', danSo: 1, loai: 'Xã' },
                    { ten: 'Hiệp Hòa', danSo: 1, loai: 'Xã' },
                    { ten: 'Hòa Bình', danSo: 1, loai: 'Xã' },
                    { ten: 'Hưng Nhân', danSo: 1, loai: 'Xã' },
                    { ten: 'Hùng Tiến', danSo: 1, loai: 'Xã' },
                    { ten: 'Liên Am', danSo: 1, loai: 'Xã' },
                    { ten: 'Lý Học', danSo: 1, loai: 'Xã' },
                    { ten: 'Nhân Hòa', danSo: 1, loai: 'Xã' },
                    { ten: 'Tam Cường', danSo: 1, loai: 'Xã' },
                    { ten: 'Tam Đa', danSo: 1, loai: 'Xã' },
                    { ten: 'Tân Hưng', danSo: 1, loai: 'Xã' },
                    { ten: 'Tân Liên', danSo: 1, loai: 'Xã' },
                    { ten: 'Thắng Thủy', danSo: 1, loai: 'Xã' },
                    { ten: 'Thanh Lương', danSo: 1, loai: 'Xã' },
                    { ten: 'Tiền Phong', danSo: 1, loai: 'Xã' },
                    { ten: 'Trấn Dương', danSo: 1, loai: 'Xã' },
                    { ten: 'Trung Lập', danSo: 1, loai: 'Xã' },
                    { ten: 'Việt Tiến', danSo: 1, loai: 'Xã' },
                    { ten: 'Vĩnh An', danSo: 1, loai: 'Xã' },
                    { ten: 'Vĩnh Long', danSo: 1, loai: 'Xã' },
                    { ten: 'Vĩnh Phong', danSo: 1, loai: 'Xã' },
                    { ten: 'Vinh Quang', danSo: 1, loai: 'Xã' },
                    { ten: 'Vĩnh Tiến', danSo: 1, loai: 'Xã' },
                ],
            },
        ],
    },
    {
        ten: 'Đà Nẵng',
        loai: 'Thành phố trực thuộc trung ương',
        danSo: 1134310,
        thanhPhan: [
            {
                ten: 'Cẩm Lệ',
                danSo: 159295,
                loai: 'Quận',
                thanhPhan: [
                    { ten: 'Hòa An', danSo: 1, loai: 'Phường' },
                    { ten: 'Hòa Phát', danSo: 1, loai: 'Phường' },
                    { ten: 'Hòa Thọ Đông', danSo: 1, loai: 'Phường' },
                    { ten: 'Hòa Thọ Tây', danSo: 1, loai: 'Phường' },
                    { ten: 'Hòa Xuân', danSo: 1, loai: 'Phường' },
                    { ten: 'Khuê Trung', danSo: 1, loai: 'Phường' },
                ],
            },
            {
                ten: 'Hải Châu',
                danSo: 201522,
                loai: 'Quận',
                thanhPhan: [
                    { ten: 'Bình Hiên', danSo: 1, loai: 'Phường' },
                    { ten: 'Bình Thuận', danSo: 1, loai: 'Phường' },
                    { ten: 'Hải Châu I', danSo: 1, loai: 'Phường' },
                    { ten: 'Hải Châu II', danSo: 1, loai: 'Phường' },
                    { ten: 'Hòa Cường Bắc', danSo: 1, loai: 'Phường' },
                    { ten: 'Hòa Cường Nam', danSo: 1, loai: 'Phường' },
                    { ten: 'Hòa Thuận Đông', danSo: 1, loai: 'Phường' },
                    { ten: 'Hòa Thuận Tây', danSo: 1, loai: 'Phường' },
                    { ten: 'Nam Dương', danSo: 1, loai: 'Phường' },
                    { ten: 'Phước Ninh', danSo: 1, loai: 'Phường' },
                    { ten: 'Thạch Thang', danSo: 1, loai: 'Phường' },
                    { ten: 'Thanh Bình', danSo: 1, loai: 'Phường' },
                    { ten: 'Thuận Phước', danSo: 1, loai: 'Phường' },
                ],
            },
            {
                ten: 'Liên Chiểu',
                danSo: 194913,
                loai: 'Quận',
                thanhPhan: [
                    { ten: 'Hòa Hiệp Bắc', danSo: 1, loai: 'Phường' },
                    { ten: 'Hòa Hiệp Nam', danSo: 1, loai: 'Phường' },
                    { ten: 'Hòa Khánh Bắc', danSo: 1, loai: 'Phường' },
                    { ten: 'Hòa Khánh Nam', danSo: 1, loai: 'Phường' },
                    { ten: 'Hòa Minh', danSo: 1, loai: 'Phường' },
                ],
            },
            {
                ten: 'Ngũ Hành Sơn',
                danSo: 90352,
                loai: 'Quận',
                thanhPhan: [
                    { ten: 'Hòa Hải', danSo: 1, loai: 'Phường' },
                    { ten: 'Hòa Quý', danSo: 1, loai: 'Phường' },
                    { ten: 'Khuê Mỹ', danSo: 1, loai: 'Phường' },
                    { ten: 'Mỹ An', danSo: 1, loai: 'Phường' },
                ],
            },
            {
                ten: 'Sơn Trà',
                danSo: 157415,
                loai: 'Quận',
                thanhPhan: [
                    { ten: 'An Hải Bắc', danSo: 1, loai: 'Phường' },
                    { ten: 'An Hải Đông', danSo: 1, loai: 'Phường' },
                    { ten: 'An Hải Tây', danSo: 1, loai: 'Phường' },
                    { ten: 'Mân Thái', danSo: 1, loai: 'Phường' },
                    { ten: 'Nại Hiên Đông', danSo: 1, loai: 'Phường' },
                    { ten: 'Phước Mỹ', danSo: 1, loai: 'Phường' },
                    { ten: 'Thọ Quang', danSo: 1, loai: 'Phường' },
                ],
            },
            {
                ten: 'Thanh Khê',
                danSo: 185064,
                loai: 'Quận',
                thanhPhan: [
                    { ten: 'An Khê', danSo: 1, loai: 'Phường' },
                    { ten: 'Chính Gián', danSo: 1, loai: 'Phường' },
                    { ten: 'Hòa Khê', danSo: 1, loai: 'Phường' },
                    { ten: 'Tam Thuận', danSo: 1, loai: 'Phường' },
                    { ten: 'Tân Chính', danSo: 1, loai: 'Phường' },
                    { ten: 'Thạc Gián', danSo: 1, loai: 'Phường' },
                    { ten: 'Thanh Khê Đông', danSo: 1, loai: 'Phường' },
                    { ten: 'Thanh Khê Tây', danSo: 1, loai: 'Phường' },
                    { ten: 'Vĩnh Trung', danSo: 1, loai: 'Phường' },
                    { ten: 'Xuân Hà', danSo: 1, loai: 'Phường' },
                ],
            },
            {
                ten: 'Hòa Vang',
                danSo: 145749,
                loai: 'Huyện',
                thanhPhan: [
                    { ten: 'Hòa Bắc', danSo: 1, loai: 'Xã' },
                    { ten: 'Hòa Châu', danSo: 1, loai: 'Xã' },
                    { ten: 'Hòa Khương', danSo: 1, loai: 'Xã' },
                    { ten: 'Hòa Liên', danSo: 1, loai: 'Xã' },
                    { ten: 'Hòa Nhơn', danSo: 1, loai: 'Xã' },
                    { ten: 'Hòa Ninh', danSo: 1, loai: 'Xã' },
                    { ten: 'Hòa Phong', danSo: 1, loai: 'Xã' },
                    { ten: 'Hòa Phú', danSo: 1, loai: 'Xã' },
                    { ten: 'Hòa Phước', danSo: 1, loai: 'Xã' },
                    { ten: 'Hòa Sơn', danSo: 1, loai: 'Xã' },
                    { ten: 'Hòa Tiến', danSo: 1, loai: 'Xã' },
                ],
            },
            { ten: 'Hoàng Sa', danSo: 1, loai: 'Huyện', thanhPhan: [] },
        ],
    },
    {
        ten: 'Cần Thơ',
        loai: 'Thành phố trực thuộc trung ương',
        danSo: 1235171,
        thanhPhan: [
            {
                ten: 'Bình Thủy',
                danSo: 140.007,
                loai: 'Quận',
                thanhPhan: [
                    { ten: 'An Thới', danSo: 1, loai: 'Phường' },
                    { ten: 'Bình Thủy', danSo: 1, loai: 'Phường' },
                    { ten: 'Bùi Hữu Nghĩa', danSo: 1, loai: 'Phường' },
                    { ten: 'Long Hòa', danSo: 1, loai: 'Phường' },
                    { ten: 'Long Tuyền', danSo: 1, loai: 'Phường' },
                    { ten: 'Thới An Đông', danSo: 1, loai: 'Phường' },
                    { ten: 'Trà An', danSo: 1, loai: 'Phường' },
                    { ten: 'Trà Nóc', danSo: 1, loai: 'Phường' },
                ],
            },
            {
                ten: 'Cái Răng',
                danSo: 165.057,
                loai: 'Quận',
                thanhPhan: [
                    { ten: 'Ba Láng', danSo: 1, loai: 'Phường' },
                    { ten: 'Hưng Phú', danSo: 1, loai: 'Phường' },
                    { ten: 'Hưng Thạnh', danSo: 1, loai: 'Phường' },
                    { ten: 'Lê Bình', danSo: 1, loai: 'Phường' },
                    { ten: 'Phú Thứ', danSo: 1, loai: 'Phường' },
                    { ten: 'Tân Phú', danSo: 1, loai: 'Phường' },
                    { ten: 'Thường Thạnh', danSo: 1, loai: 'Phường' },
                ],
            },
            {
                ten: 'Ninh Kiều',
                danSo: 280.494,
                loai: 'Quận',
                thanhPhan: [
                    { ten: 'An Bình', danSo: 1, loai: 'Phường' },
                    { ten: 'An Cư', danSo: 1, loai: 'Phường' },
                    { ten: 'An Hoà', danSo: 1, loai: 'Phường' },
                    { ten: 'An Khánh', danSo: 1, loai: 'Phường' },
                    { ten: 'An Nghiệp', danSo: 1, loai: 'Phường' },
                    { ten: 'An Phú', danSo: 1, loai: 'Phường' },
                    { ten: 'Cái Khế', danSo: 1, loai: 'Phường' },
                    { ten: 'Hưng Lợi', danSo: 1, loai: 'Phường' },
                    { ten: 'Tân An', danSo: 1, loai: 'Phường' },
                    { ten: 'Thới Bình', danSo: 1, loai: 'Phường' },
                    { ten: 'Xuân Khánh', danSo: 1, loai: 'Phường' },
                ],
            },
            {
                ten: 'Ô Môn',
                danSo: 160.35,
                loai: 'Quận',
                thanhPhan: [
                    { ten: 'Châu Văn Liêm', danSo: 1, loai: 'Phường' },
                    { ten: 'Long Hưng', danSo: 1, loai: 'Phường' },
                    { ten: 'Phước Thới', danSo: 1, loai: 'Phường' },
                    { ten: 'Thới An', danSo: 1, loai: 'Phường' },
                    { ten: 'Thới Hoà', danSo: 1, loai: 'Phường' },
                    { ten: 'Thới Long', danSo: 1, loai: 'Phường' },
                    { ten: 'Trường Lạc', danSo: 1, loai: 'Phường' },
                ],
            },
            {
                ten: 'Thốt Nốt',
                danSo: 155.36,
                loai: 'Quận',
                thanhPhan: [
                    { ten: 'Tân Hưng', danSo: 1, loai: 'Phường' },
                    { ten: 'Tân Lộc', danSo: 1, loai: 'Phường' },
                    { ten: 'Thạnh Hòa', danSo: 1, loai: 'Phường' },
                    { ten: 'Thốt Nốt', danSo: 1, loai: 'Phường' },
                    { ten: 'Thới Thuận', danSo: 1, loai: 'Phường' },
                    { ten: 'Thuận An', danSo: 1, loai: 'Phường' },
                    { ten: 'Thuận Hưng', danSo: 1, loai: 'Phường' },
                    { ten: 'Trung Kiên', danSo: 1, loai: 'Phường' },
                    { ten: 'Trung Nhứt', danSo: 1, loai: 'Phường' },
                ],
            },
            {
                ten: 'Cờ Đỏ',
                danSo: 135.709,
                loai: 'Huyện',
                thanhPhan: [
                    { ten: 'Cờ Đỏ', danSo: 1, loai: 'Thị trấn' },
                    { ten: 'Đông Hiệp', danSo: 1, loai: 'Xã' },
                    { ten: 'Đông Thắng', danSo: 1, loai: 'Xã' },
                    { ten: 'Thạnh Phú', danSo: 1, loai: 'Xã' },
                    { ten: 'Thới Đông', danSo: 1, loai: 'Xã' },
                    { ten: 'Thới Hưng', danSo: 1, loai: 'Xã' },
                    { ten: 'Thới Xuân', danSo: 1, loai: 'Xã' },
                    { ten: 'Trung An', danSo: 1, loai: 'Xã' },
                    { ten: 'Trung Hưng', danSo: 1, loai: 'Xã' },
                    { ten: 'Trung Thạnh', danSo: 1, loai: 'Xã' },
                ],
            },
            {
                ten: 'Phong Điền',
                danSo: 123.136,
                loai: 'Huyện',
                thanhPhan: [
                    { ten: 'Phong Điền', danSo: 1, loai: 'Thị trấn' },
                    { ten: 'Giai Xuân', danSo: 1, loai: 'Xã' },
                    { ten: 'Mỹ Khánh', danSo: 1, loai: 'Xã' },
                    { ten: 'Nhơn Ái', danSo: 1, loai: 'Xã' },
                    { ten: 'Nhơn Nghĩa', danSo: 1, loai: 'Xã' },
                    { ten: 'Tân Thới', danSo: 1, loai: 'Xã' },
                    { ten: 'Trường Long', danSo: 1, loai: 'Xã' },
                ],
            },
            {
                ten: 'Thới Lai',
                danSo: 148.0,
                loai: 'Huyện',
                thanhPhan: [
                    { ten: 'Thới Lai', danSo: 1, loai: 'Thị trấn' },
                    { ten: 'Định Môn', danSo: 1, loai: 'Xã' },
                    { ten: 'Đông Bình', danSo: 1, loai: 'Xã' },
                    { ten: 'Đông Thuận', danSo: 1, loai: 'Xã' },
                    { ten: 'Tân Thạnh', danSo: 1, loai: 'Xã' },
                    { ten: 'Thới Tân', danSo: 1, loai: 'Xã' },
                    { ten: 'Thới Thạnh', danSo: 1, loai: 'Xã' },
                    { ten: 'Trường Thắng', danSo: 1, loai: 'Xã' },
                    { ten: 'Trường Thành', danSo: 1, loai: 'Xã' },
                    { ten: 'Trường Xuân', danSo: 1, loai: 'Xã' },
                    { ten: 'Trường Xuân A', danSo: 1, loai: 'Xã' },
                    { ten: 'Trường Xuân B', danSo: 1, loai: 'Xã' },
                    { ten: 'Xuân Thắng', danSo: 1, loai: 'Xã' },
                ],
            },
            {
                ten: 'Vĩnh Thạnh',
                danSo: 152.2,
                loai: 'Huyện',
                thanhPhan: [
                    { ten: 'Vĩnh Thạnh', danSo: 1, loai: 'Thị trấn' },
                    { ten: 'Thạnh An', danSo: 1, loai: 'Thị trấn' },
                    { ten: 'Thạnh An', danSo: 1, loai: 'Xã' },
                    { ten: 'Thạnh Lộc', danSo: 1, loai: 'Xã' },
                    { ten: 'Thạnh Lợi', danSo: 1, loai: 'Xã' },
                    { ten: 'Thạnh Mỹ', danSo: 1, loai: 'Xã' },
                    { ten: 'Thạnh Quới', danSo: 1, loai: 'Xã' },
                    { ten: 'Thạnh Thắng', danSo: 1, loai: 'Xã' },
                    { ten: 'Thạnh Tiến', danSo: 1, loai: 'Xã' },
                    { ten: 'Vĩnh Bình', danSo: 1, loai: 'Xã' },
                    { ten: 'Vĩnh Trinh', danSo: 1, loai: 'Xã' },
                ],
            },
        ],
    },

    // { ten: 'Lai Châu', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Điện Biên', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Lào Cai', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Hà Giang', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Cao Bằng', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Lạng Sơn', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Yên Bái', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Tuyên Quang', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Bắc Kạn', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Thái Nguyên', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Sơn La', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Phú Thọ', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Vĩnh Phúc', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Bắc Ninh', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Bắc Giang', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Quảng Ninh', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Hòa Bình', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Hưng Yên', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Hải Dương', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Thái Bình', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Hà Nam', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Nam Định', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Ninh Bình', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Thanh Hóa', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Nghệ An', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Hà Tĩnh', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Quảng Bình', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Quảng Trị', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Thừa Thiên-Huế', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Quảng Nam', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Quảng Ngãi', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Kon Tum', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Gia Lai', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Bình Định', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Phú Yên', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Đắk Lắk', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Đắk Nông', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Khánh Hòa', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Lâm Đồng', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Ninh Thuận', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Bình Thuận', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Bình Phước', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Tây Ninh', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Bình Dương', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Đồng Nai', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Bà Rịa-Vũng Tàu', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Long An', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Đồng Tháp', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Tiền Giang', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Bến Tre', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'An Giang', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Vĩnh Long', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Kiên Giang', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Hậu Giang', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Trà Vinh', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Sóc Trăng', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Bạc Liêu', loai: 'Tỉnh', thanhPhan: [] },
    // { ten: 'Cà Mau', loai: 'Tỉnh', thanhPhan: [] },
];
