module.exports.coDinh = {
    nhaMang: [
        { ten: 'Viettel', cacDauSo: ['220', '221', '222', '223', '224', '246', '247', '248', '249', '625', '626', '627', '628', '629', '633', '664', '665', '666', '667', '668', '669'] },
        { ten: 'VNPT', cacDauSo: ['35', '36', '37', '38', '39'] },
        { ten: 'Saigon Postel (SPT)', cacDauSo: ['540', '541', '541', '543', '544'] },
        { ten: 'CMC', cacDauSo: ['71'] },
        { ten: 'VTC', cacDauSo: ['445', '450'] },
        { ten: 'Đông Dương Telecom (Indochina Telecom)', cacDauSo: ['7779'] },
        { ten: 'FPT', cacDauSo: ['73'] },
    ],
    maVung: [
        { tenTinh: 'Lai Châu', ma: '213' },
        { tenTinh: 'Điện Biên', ma: '215' },
        { tenTinh: 'Lào Cai', ma: '214' },
        { tenTinh: 'Yên Bái', ma: '216' },
        { tenTinh: 'Sơn La', ma: '212' },
        { tenTinh: 'Hà Giang', ma: '219' },
        { tenTinh: 'Tuyên Quang', ma: '207' },
        { tenTinh: 'Phú Thọ', ma: '210' },
        { tenTinh: 'Hòa Bình', ma: '218' },
        { tenTinh: 'Cao Bằng', ma: '206' },
        { tenTinh: 'Bắc Cạn', ma: '209' },
        { tenTinh: 'Thái Nguyên', ma: '208' },
        { tenTinh: 'Vĩnh Phúc', ma: '211' },
        { tenTinh: 'Hà Nội', ma: '24' },
        { tenTinh: 'Lạng Sơn', ma: '205' },
        { tenTinh: 'Bắc Giang', ma: '204' },
        { tenTinh: 'Bắc Ninh', ma: '222' },
        { tenTinh: 'Hưng Yên', ma: '221' },
        { tenTinh: 'Hà Nam', ma: '226' },
        { tenTinh: 'Ninh Bình', ma: '229' },
        { tenTinh: 'Quảng Ninh', ma: '203' },
        { tenTinh: 'Hải Dương', ma: '220' },
        { tenTinh: 'Hải Phòng', ma: '225' },
        { tenTinh: 'Thái Bình', ma: '227' },
        { tenTinh: 'Nam Định', ma: '228' },
        { tenTinh: 'Thanh Hóa', ma: '237' },
        { tenTinh: 'Nghệ An', ma: '238' },
        { tenTinh: 'Hà Tĩnh', ma: '239' },
        { tenTinh: 'Quảng Bình', ma: '232' },
        { tenTinh: 'Quảng Trị', ma: '233' },
        { tenTinh: 'Huế', ma: '234' },
        { tenTinh: 'Đà Nẵng', ma: '236' },
        { tenTinh: 'Quảng Nam', ma: '235' },
        { tenTinh: 'Quảng Ngãi', ma: '255' },
        { tenTinh: 'Kon Tum', ma: '260' },
        { tenTinh: 'Gia Lai', ma: '269' },
        { tenTinh: 'Bình Định', ma: '256' },
        { tenTinh: 'Đắk Lắk', ma: '262' },
        { tenTinh: 'Phú Yên', ma: '257' },
        { tenTinh: 'Khánh Hòa', ma: '258' },
        { tenTinh: 'Ninh Thuận', ma: '259' },
        { tenTinh: 'Đắk Nông', ma: '261' },
        { tenTinh: 'Lâm Đồng', ma: '263' },
        { tenTinh: 'Bình Thuận', ma: '252' },
        { tenTinh: 'Bình Phước', ma: '271' },
        { tenTinh: 'Đồng Nai', ma: '251' },
        { tenTinh: 'Bà Rịa - Vũng Tàu', ma: '254' },
        { tenTinh: 'Tây Ninh', ma: '276' },
        { tenTinh: 'Bình Dương', ma: '274' },
        { tenTinh: 'Thành phố Hồ Chí Minh', ma: '28' },
        { tenTinh: 'Long An', ma: '272' },
        { tenTinh: 'Tiền Giang', ma: '273' },
        { tenTinh: 'Đồng Tháp', ma: '277' },
        { tenTinh: 'Bến Tre', ma: '275' },
        { tenTinh: 'An Giang', ma: '296' },
        { tenTinh: 'Vĩnh Long', ma: '270' },
        { tenTinh: 'Trà Vinh', ma: '294' },
        { tenTinh: 'Cần Thơ', ma: '292' },
        { tenTinh: 'Hận Giang', ma: '293' },
        { tenTinh: 'Sóc Trăng', ma: '299' },
        { tenTinh: 'Kiên Giang', ma: '297' },
        { tenTinh: 'Bạc Liêu', ma: '291' },
        { tenTinh: 'Cà Mau', ma: '290' },
    ],
};
module.exports.diDong = [
    { nhaMang: 'Viettel', cacDauSo: ['96', '97', '98', '86', '87', '88'] },
    { nhaMang: 'Mobiphone', cacDauSo: ['90', '93', '89'] },
    { nhaMang: 'Vinaphone', cacDauSo: ['91', '94', '88'] },
    { nhaMang: 'Vietnamobile', cacDauSo: ['92', '93', '94', '95', '96', '97'] },
    { nhaMang: 'Gmobile', cacDauSo: ['99'] },
];
